<section class="app_content recargas">
    <div class="box_center">
        <div class="app_box">
            <div class="menu right_active">
                <ul>
                    <li class="first"><a href="<?php echo BASE_URL; ?>beneficios">Beneficios</a></li>
                    <li><a href="<?php echo BASE_URL; ?>mis-tarjetas">Mis tarjetas</a></li>
                    <li class="last active"><a href="<?php echo BASE_URL; ?>recargas">Recargas</a></li>
                </ul>
            </div>
            <div class="purple_box">
                <p class="yellow_text small_text">Recarga de mis tarjetas</p>
                
                <a href="<?php echo BASE_URL ?>carrito" class="cart_box active">
                    <span class="label">Items en el carrito:</span>
                    <div class="cart">
                        <span class="icon"></span>
                        <span class="number"><?php echo empty($cartModel) ? 0 : $cartModel->getQuantityCart(); ?></span>
                    </div>
                </a>
                <br><br>
                <div class="pay_box_white cart_page">
                    <div class="left">
                        <?php if (empty($cartModel)) : ?>
                        <div class="empty_cart">
                            <span class="icon"></span>
                            <h2>¡Tu carrito esta vacío!</h2>
                            <p>Puedes ver todo lo que tenemos para ti en</p>
                            <a href="<?php echo BASE_URL; ?>recargas" class="link_orange">Promociones y recargas</a>
                        </div>
                        <?php else : ?>
                        <div class="items_cart">
                            <?php $index = 0; ?>
                            <?php foreach ($cartModel->getProductsCart() as $productos) : ?>
                                <?php foreach ($productos as $producto) : ?>
                                    <?php $index++; ?>
                                    <div class="item">
                                        <div class="left">
                                            <img width="140" height="71" src="<?php echo $urlImg . '/' . $producto->getProductImage(); ?>" alt="<?php echo $producto->getProductName(); ?>"/>
                                        </div>
                                        <div class="right" data-prefix="<?php echo $index; ?>">
                                            <span class="remove_icon">x</span>
                                            <h5><?php echo $producto->getProductName(); ?> <span>. </span>
                                                <?php if ($producto->getOption('legal') != '') : ?>
                                                <a href="#modal_watch_legal_<?php echo $index; ?>" name="modal" class="legal">Ver legal</a>
                                                <?php endif; ?>
                                            </h5>
                                            <h4 class="item_title">
                                                <?php echo $producto->getProductName2(); ?>
                                            </h4>
                                            <div class="card_type">
                                                <span>En:</span>
                                                <div class="card_name">
                                                    <span></span>
                                                    <select id="tarjeta_<?php echo $index; ?>" class="change_card" data-pre="<?php echo $producto->getCategoryCode(); ?>">
                                                        <?php foreach ($usuarioTarjetas as $codigo => $nombre) : ?>
                                                        <?php $select = ($codigo == $producto->getCategoryCode()) ? 'selected="selected"' : ''; ?>
                                                        <option value="<?php echo $codigo; ?>" <?php echo $select; ?>><?php echo $nombre; ?></option>
                                                        <?php endforeach; ?>
                                                    </select>
                                                </div>
                                                <select id="cantidad_<?php echo $index; ?>" class="cant change_cant"> 
                                                    <?php foreach ($catidades as $key => $value) : ?>
                                                    <?php $select = ($key == $producto->getQuantity()) ? 'selected="selected"' : ''; ?>
                                                    <option value="<?php echo $key; ?>" <?php echo $select; ?>><?php echo $value; ?></option>
                                                    <?php endforeach ?>
                                                </select>
                                                <input id="id_<?php echo $index; ?>" type="hidden" value="<?php echo $producto->getProductId(); ?>">
                                            </div>
                                            <div class="detail">
                                                <?php if (\Common\Helpers\Util::noEmptyDecimal($producto->getOption('emoney'))) : ?>
                                                <div class="line">
                                                    <div class="left">Dinero</div>
                                                    <div class="right">S/. <?php echo $producto->getOption('emoney', true); ?></div>
                                                </div>
                                                <?php endif; ?>
                                                <?php if (\Common\Helpers\Util::noEmptyDecimal($producto->getOption('bonus'))) : ?>
                                                <div class="line">
                                                    <div class="left">Coney Bonus</div>
                                                    <div class="right">S/. <?php echo $producto->getOption('bonus', true); ?></div>
                                                </div>
                                                <?php endif; ?>
                                                <?php if (\Common\Helpers\Util::noEmptyDecimal($producto->getOption('promotionbonus'))) : ?>
                                                <div class="line">
                                                    <div class="left">Coney Bonus Plus</div>
                                                    <div class="right">S/. <?php echo $producto->getOption('promotionbonus', true); ?></div>
                                                </div>
                                                <?php endif; ?>
                                                <?php if (\Common\Helpers\Util::noEmptyDecimal($producto->getOption('etickets'))) : ?>
                                                <div class="line">
                                                    <div class="left">Tickets</div>
                                                    <div class="right"><?php echo $producto->getOption('etickets'); ?></div>
                                                </div>
                                                <?php endif; ?>
                                            </div>
                                            <div class="link_show">
                                                <div class="watch_detail">Ver detalle</div>
                                                <div class="hidden_detail">Ocultar detalle</div>
                                            </div>
                                            <?php $partMonto = explode('.', $producto->getAmount(true)); ?>
                                            <div class="total">S/. <span><?php echo $partMonto[0]; ?></span>.<?php echo $partMonto[1]; ?> </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </div>
                        <?php endif; ?>
                    </div>
                    <div class="right">
                        <h4>Pago total</h4>
                        <div align="center" class="total_box">
                            <?php $montoTotal = empty($cartModel) ? '0.00' : $cartModel->getAmountCart(true); ?>
                            <?php $partMontoTotal = explode('.', $montoTotal); ?>
                            <h3>
                                <span class="medium">S/. </span>
                                <span class="large"><?php echo $partMontoTotal[0]; ?></span>
                                <span class="medium">.<?php echo $partMontoTotal[1]; ?></span>
                            </h3>
                            <button class="btn btn_orange" onclick="location.href='<?php echo BASE_URL; ?>carrito/pagos'">Pagar</button>
                            <a href="<?php echo BASE_URL; ?>recargas" class="link_orange">Seguir comprando  </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--promociones-->
        <p class="yellow_text small_text">¡Añade más promociones!</p>
        <div class="offers_box_three carrito_offers">
            <?php foreach ($promociones['normal'] as $key => $row) : ?>
                <?php $float = (($key+1)%3 == 0) ? 'right' : 'left'; ?>
                <div class="col_3 <?php echo $float; ?>">
                    <div class="box_white">
                        <div class="image"><a href="<?php echo BASE_URL ?>recargas"><img src="<?php echo $urlImg . '/' . $row['imagen']; ?>" alt="<?php echo $row['titulo1']; ?>"/></a></div>
                        <p class="breadcrumb" style="text-align:center;"><?php echo $row['titulo1']; ?> 
                            <?php if (!empty($row['legal'])) : ?>
                            <a href="#modal_watch_legal_nor_<?php echo $key; ?>" name="modal" class="watch_legal">. Ver legal</a>
                            <?php endif; ?>
                        </p>
                        <p><?php echo $row['titulo2']; ?></p>
                    </div>
                    <button class="btn btn_orange btnComprar">Comprar</button>
                </div>
            <?php endforeach; ?>
        </div>
        <!--fin promociones-->
    </div>
    <?php foreach ($promociones['normal'] as $key => $row) : ?>
        <div id="modal_watch_legal_nor_<?php echo $key; ?>" class="modal_box modal_box_legal">
            <div class="modal_content">
                <h3>Importante: <span></span></h3>
                <hr/>
                <div class="text_box">
                    <p><?php echo $row['legal']; ?></p>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    
    <?php if (!empty($cartModel)) : ?>
    <?php $index = 0; ?>
    <?php foreach ($cartModel->getProductsCart() as $productos) : ?>
        <?php foreach ($productos as $producto) : ?>
            <?php $index++; ?>
                <div id="modal_watch_legal_<?php echo $index;?>" class="modal_box modal_box_legal">
                  <div class="modal_content">
                    <h3>Importante: <span></span></h3>
                    <hr/>
                    <div class="text_box">
                      <p><?php echo $producto->getOption('legal'); ?></p>
                    </div>
                  </div>
                </div>
        <?php endforeach; ?>
    <?php endforeach; ?>
    <?php endif; ?>
    <div id="mask"></div>
</section>
<script type="text/javascript">
    $(document).ready(function(){
        $('.btnComprar').click(function(){location.href = '<?php echo BASE_URL ?>recargas';});
    });
</script>