<section class="app_content recargas">
    <div class="box_center">
        <div class="app_box">
            <div class="menu right_active">
                <ul>
                    <li class="first"><a href="<?php echo BASE_URL; ?>beneficios">Beneficios</a></li>
                    <li><a href="<?php echo BASE_URL; ?>mis-tarjetas">Mis tarjetas</a></li>
                    <li class="last active"><a href="<?php echo BASE_URL; ?>recargas">Recargas</a></li>
                </ul>
            </div>
            <div class="purple_box">
                <p class="yellow_text small_text">Recarga de mis tarjetas</p>
                
                <a href="<?php echo BASE_URL ?>carrito" class="cart_box active">
                    <span class="label">Items en el carrito:</span>
                    <div class="cart">
                        <span class="icon"></span>
                        <span class="number"><?php echo empty($cartModel) ? 0 : $cartModel->getQuantityCart(); ?></span>
                    </div>
                </a>
                <br><br>
                <div class="pay_box_white cart_page">
                    <div class="left">
                        <?php if (empty($cartModel)) : ?>
                        <div class="empty_cart">
                            <span class="icon"></span>
                            <h2>¡Tu carrito esta vacío!</h2>
                            <p>Puedes ver todo lo que tenemos para ti en</p>
                            <a href="<?php echo BASE_URL; ?>recargas" class="link_orange">Promociones y recargas</a>
                        </div>
                        <?php else : ?>
                        <div class="items_cart">
                            <?php $index = 0; ?>
                            <?php foreach ($cartModel->getProductsCart() as $productos) : ?>
                                <?php foreach ($productos as $producto) : ?>
                                    <?php $index++; ?>
                                    <div class="item">
                                        <div class="left">
                                            <img width="140" height="71" src="<?php echo $urlImg . '/' . $producto->getProductImage(); ?>" alt="<?php echo $producto->getProductName(); ?>"/>
                                        </div>
                                        <div class="right" data-prefix="<?php echo $index; ?>">
                                            <span class="remove_icon">x</span>
                                            <h5><?php echo $producto->getProductName(); ?> <span>. </span>
                                                <a href="#modal_watch_legal" name="modal" class="legal">Ver legal</a>
                                            </h5>
                                            <h4 class="item_title">
                                                <?php echo $producto->getProductName2(); ?>
                                            </h4>
                                            <div class="card_type">
                                                <span>En:</span>
                                                <div class="card_name">
                                                    <span></span>
                                                    <select id="tarjeta_<?php echo $index; ?>" class="change_card" data-pre="<?php echo $producto->getCategoryCode(); ?>">
                                                        <?php foreach ($usuarioTarjetas as $codigo => $nombre) : ?>
                                                        <?php $select = ($codigo == $producto->getCategoryCode()) ? 'selected="selected"' : ''; ?>
                                                        <option value="<?php echo $codigo; ?>" <?php echo $select; ?>><?php echo $nombre; ?></option>
                                                        <?php endforeach; ?>
                                                    </select>
                                                </div>
                                                <select id="cantidad_<?php echo $index; ?>" class="cant change_cant"> 
                                                    <?php foreach ($cattidades as $key => $value) : ?>
                                                    <?php $select = ($key == $producto->getQuantity()) ? 'selected="selected"' : ''; ?>
                                                    <option value="<?php echo $key; ?>" <?php echo $select; ?>><?php echo $value; ?></option>
                                                    <?php endforeach ?>
                                                </select>
                                                <input id="id_<?php echo $index; ?>" type="hidden" value="<?php echo $producto->getProductId(); ?>">
                                            </div>
                                            <div class="detail">
                                                <?php if (\Common\Helpers\Util::noEmptyDecimal($producto->getOption('emoney'))) : ?>
                                                <div class="line">
                                                    <div class="left">Dinero</div>
                                                    <div class="right">S/. <?php echo $producto->getOption('emoney', true); ?></div>
                                                </div>
                                                <?php endif; ?>
                                                <?php if (\Common\Helpers\Util::noEmptyDecimal($producto->getOption('bonus'))) : ?>
                                                <div class="line">
                                                    <div class="left">Coney Bonus</div>
                                                    <div class="right">S/. <?php echo $producto->getOption('bonus', true); ?></div>
                                                </div>
                                                <?php endif; ?>
                                                <?php if (\Common\Helpers\Util::noEmptyDecimal($producto->getOption('promotionbonus'))) : ?>
                                                <div class="line">
                                                    <div class="left">Coney Bonus Plus</div>
                                                    <div class="right">S/. <?php echo $producto->getOption('promotionbonus', true); ?></div>
                                                </div>
                                                <?php endif; ?>
                                                <?php if (\Common\Helpers\Util::noEmptyDecimal($producto->getOption('etickets'))) : ?>
                                                <div class="line">
                                                    <div class="left">Tickets</div>
                                                    <div class="right"><?php echo $producto->getOption('etickets'); ?></div>
                                                </div>
                                                <?php endif; ?>
                                            </div>
                                            <div class="link_show">
                                                <div class="watch_detail">Ver detalle</div>
                                                <div class="hidden_detail">Ocultar detalle</div>
                                            </div>
                                            <?php $partMonto = explode('.', $producto->getAmount(true)); ?>
                                            <div class="total">S/. <span><?php echo $partMonto[0]; ?></span>.<?php echo $partMonto[1]; ?> </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </div>
                        <?php endif; ?>
                    </div>
                    <div class="right">
                        <h4>Pago total</h4>
                        <div align="center" class="total_box">
                            <?php $montoTotal = empty($cartModel) ? '0.00' : $cartModel->getAmountCart(true); ?>
                            <?php $partMontoTotal = explode('.', $montoTotal); ?>
                            <h3>
                                <span class="medium">S/. </span>
                                <span class="large"><?php echo $partMontoTotal[0]; ?></span>
                                <span class="medium">.<?php echo $partMontoTotal[1]; ?></span>
                            </h3>
                            <button class="btn btn_orange" onclick="location.href='<?php echo BASE_URL; ?>carrito/pagos'">Pagar</button>
                            <a href="<?php echo BASE_URL; ?>recargas" class="link_orange">Seguir comprando  </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <div id="modal_watch_legal" class="modal_box">
      <div class="modal_content">
        <h3>Importante:</h3>
        <hr/>
        <div class="text_box">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt leo erat. Maecenas dapibus, diam quis dapibus elementum, risus diam congue risus, vitae tristique magna orci et sem. Aliquam congue ut tellus eu ultricies. Vestibulum tristique sapien sit amet accumsan feugiat. Integer congue suscipit dictum. Ut a nisl tempus, ornare erat at, ultrices lectus. Suspendisse pulvinar eros vel finibus ultricies. Maecenas lacinia, tellus ac egestas tincidunt, turpis ipsum pulvinar arcu, et blandit purus lectus vitae odio. Phasellus lobortis, orci non efficitur consectetur, mauris urna ornare nisl, non sodales lectus sapien ac diam. Morbi ligula lorem, tristique in cursus et, vulputate quis lorem. Suspendisse ut erat turpis. </p>
          <p>Sed sed tellus pulvinar, lobortis est sit amet, mollis lectus. Suspendisse semper vestibulum erat at lacinia. Mauris eget quam sit amet magna rutrum maximus in sed ipsum. Etiam libero justo, dictum non malesuada ut, ullamcorper at leo. Vestibulum accumsan condimentum lectus, et faucibus justo sodales non. Aliquam dictum ipsum sit amet nisl elementum commodo ut ut ligula. Aliquam sagittis fermentum gravida. Vestibulum eu neque eget neque placerat ullamcorper at sit amet mauris. Morbi tellus odio, lacinia a libero sed, congue cursus urna. </p>
          <p>Suspendisse potenti. Quisque ipsum ante, luctus quis leo sit amet, mattis convallis enim. Donec feugiat vehicula felis. In lacinia quis est eget tempus. Pellentesque vulputate augue vel nibh sagittis sollicitudin. Etiam eu laoreet tellus. Sed id fermentum lorem. Fusce feugiat, libero nec finibus egestas, tellus risus dignissim dui, ultricies condimentum lectus erat et leo. Integer semper erat sit amet ex tempor, sed eleifend libero venenatis. Proin a arcu quis arcu dapibus tristique. Fusce vehicula diam vitae diam faucibus rutrum quis et leo. Nullam ex metus, mollis eget dignissim quis, bibendum et mauris. Integer bibendum, lacus sit amet tincidunt aliquam, sapien arcu tempor nisi, eget egestas massa felis ut purus. Nulla a purus a nisl tincidunt scelerisque. Proin tempor arcu et tortor lacinia, ac pellentesque eros consectetur. Aenean eget eros in lectus auctor finibus ac nec ex.</p>
        </div>
      </div>
    </div>
    <div id="mask"></div>
</section>