<form id="formPago" action="" method="post" data-parsley-validate="true">
<section class="app_content recargas">
    <div class="box_center">
        <div class="app_box">
            <div class="menu right_active">
                <ul>
                    <li class="first"><a href="<?php echo BASE_URL; ?>beneficios">Beneficios</a></li>
                    <li><a href="<?php echo BASE_URL; ?>mis-tarjetas">Mis tarjetas</a></li>
                    <li class="last active"><a href="<?php echo BASE_URL; ?>recargas">Recargas</a></li>
                </ul>
            </div>
            <div class="purple_box">
                <p class="yellow_text small_text">Recarga de mis tarjetas</p>
                <div class="steps">
                    <div class="step active">1</div>
                    <span class="yellow"></span>
                    <div class="step active">2</div>
                </div>
                <a href="<?php echo BASE_URL ?>carrito" class="cart_box">
                    <span class="label">Items en el carrito:</span>
                    <div class="cart">
                        <span class="icon"></span>
                        <span class="number"><?php echo empty($cartModel) ? 0 : $cartModel->getQuantityCart(); ?></span>
                    </div>
                </a>
                <div class="pay_box_white">
                    <div class="left">
                        <h4>1. Datos del Pago</h4>
                        <p>Datos solicitados para la generación del comprobante</p>
                        <div class="error_message" style="display: none;"><span class="icon"></span>
                            <p id="messageError">Lo sentimos, no se pudo completar el proceso, por favor inténtelo más tarde.</p>
                        </div>
                        <div class="voucher">
                            <input type="radio" name="comprobante_tipo" checked="checked" class="boleta" value="<?php echo \Orden\Model\Service\OrdenService::TIPO_COMPROBANTE_BOLETA; ?>"/>Boleta
                            <input type="radio" name="comprobante_tipo" class="factura" value="<?php echo \Orden\Model\Service\OrdenService::TIPO_COMPROBANTE_FACTURA; ?>"/>Factura
                        </div>
                        <div class="content_boleta">
                            <div class="form_control">
                                <label for="nombres">Nombre</label>
                                <input id="nombres" name="nombres" type="text" value="<?php echo $usuarioData['nombres']; ?>" data-parsley-required="true" data-parsley-required-message="El campo es requerido y no puede estar vacío." readonly="readonly" class="disabled"/>
                            </div>
                            <div class="form_control">
                                <label for="paterno">Apellido paterno</label>
                                <input id="paterno" name="paterno" type="text" value="<?php echo $usuarioData['paterno']; ?>" data-parsley-required="true" data-parsley-required-message="El campo es requerido y no puede estar vacío." <?php echo !empty($usuarioData['paterno']) ? 'readonly="readonly"' : ''; ?> class="disabled"/>
                            </div>
                            <div class="form_control">
                                <label for="materno">Apellido materno</label>
                                <input id="materno" name="materno" type="text" value="<?php echo $usuarioData['materno']; ?>" data-parsley-required="true" data-parsley-required-message="El campo es requerido y no puede estar vacío." <?php echo !empty($usuarioData['materno']) ? 'readonly="readonly"' : ''; ?> class="disabled"/>
                            </div>
                            <div class="form_control">
                                <label for="documento_identidad">DNI/Pasaporte</label>
                                <input id="documento_numero" maxlength="8" name="documento_numero" type="text" value="<?php echo $usuarioData['di_valor']; ?>" data-parsley-required="true" data-parsley-required-message="El campo es requerido y no puede estar vacío."  <?php echo !empty($usuarioData['di_valor']) ? 'readonly="readonly"' : ''; ?> class="disabled"/>
                            </div>
                        </div>
                        <div class="content_factura">
                            <?php if (!empty($perfilPagos)) : ?>
                            <div class="form_control">
                                <label for="perfil_pago">Perfil de pago</label>
                                <select id="perfil_pago" name="perfil_pago">
                                    <option value="">Seleccione</option>
                                    <?php foreach ($perfilPagos as $key => $value) : ?>
                                        <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <?php endif; ?>
                            <div class="form_control">
                                <label for="fac_razon_social">Razón Social</label>
                                <input id="fac_razon_social" name="fac_razon_social" type="text" data-parsley-required="true" data-parsley-required-message="El campo es requerido y no puede estar vacío."/>
                            </div>
                            <div class="form_control">
                                <label for="ruc">RUC</label>
                                <input id="ruc" name="ruc" maxlength="11" type="number" data-parsley-required="true" data-parsley-required-message="El campo es requerido y no puede estar vacío." data-parsley-minlength="11" data-parsley-minlength-message="El RUC no es válido" data-parsley-maxlength="11" data-parsley-maxlength-message="El RUC no es válido" data-parsley-type="integer"/>
                            </div>
                            <div class="form_control">
                                <label for="fac_direccion_fiscal">Dirección fiscal</label>
                                <input id="fac_direccion_fiscal" name="fac_direccion_fiscal" type="text" data-parsley-required="true" data-parsley-required-message="El campo es requerido y no puede estar vacío." class="fiscal_address"/>
                            </div>
                            <div class="form_control">
                                <label for="fac_direccion_entrega_factura">Dirección de entrega de factura</label>
                                <input id="fac_direccion_entrega_factura" name="fac_direccion_entrega_factura" type="text" data-parsley-required="true" data-parsley-required-message="El campo es requerido y no puede estar vacío." class="factura_address"/>
                            </div>
                            <div class="form_control">
                                <input type="checkbox" class="equal_address"/>Misma dirección fiscal
                            </div>
                            <div class="form_control">
                                <label for="distrito_id">Distrito</label>
                                <select id="distrito_id" name="distrito_id">
                                    <option value="">Seleccione</option>
                                    <?php foreach ($distritos as $key => $value) : ?>
                                        <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="right">
                        <h4>2. Seleccione el método de pago</h4>
                        <div class="credit_cards">
                            <div class="card pagoefectivo pagoefectivo1 active"></div>
                            <div class="card pagoefectivo pagoefectivo2"></div>
                            <div class="card visa"></div>
                            <div class="cards_option">
                                <input type="radio" name="metodo_pago" value="pe" checked="checked" class="pe"/>
                                <input type="radio" name="metodo_pago" value="visa" class="visa"/>
                            </div>
                        </div>
                        <h4>3. Confirma tu compra</h4>
                        <div class="items_cart">
                            <?php $index = 0; ?>
                            <?php foreach ($cartModel->getProductsCart() as $productos) : ?>
                                <?php foreach ($productos as $producto) : ?>
                                    <?php $index++; ?>
                                    <div class="item">
                                        <div class="left">
                                            <img src="<?php echo $urlImg . '/' . $producto->getProductImage(); ?>" alt="<?php echo $producto->getProductName(); ?>"/>
                                        </div>
                                        <div class="right">
                                            <h5><?php echo $producto->getProductName(); ?><span>. </span>
                                                <?php if ($producto->getOption('legal') != '') : ?>
                                                <a href="#modal_watch_legal_<?php echo $index; ?>" name="modal" class="legal">Ver legal</a>
                                                <?php endif; ?>
                                            </h5>
                                            <h4 class="item_title"><?php echo $producto->getProductName2(); ?></h4>
                                            <div class="card_type">
                                                <span>En:</span><span class="icon_card"></span>
                                                <span class="card_name"><?php echo $producto->getCategoryName(); ?></span>
                                                <span class="cant">Cantidad: <?php echo $producto->getQuantity(); ?></span>
                                            </div>
                                            <div class="detail">
                                                <?php if (\Common\Helpers\Util::noEmptyDecimal($producto->getOption('emoney'))) : ?>
                                                <div class="line">
                                                    <div class="left">Dinero</div>
                                                    <div class="right">S/. <?php echo $producto->getOption('emoney', true); ?></div>
                                                </div>
                                                <?php endif; ?>
                                                <?php if (\Common\Helpers\Util::noEmptyDecimal($producto->getOption('bonus'))) : ?>
                                                <div class="line">
                                                    <div class="left">Coney Bonos</div>
                                                    <div class="right">S/. <?php echo $producto->getOption('bonus', true); ?></div>
                                                </div>
                                                <?php endif; ?>
                                                <?php if (\Common\Helpers\Util::noEmptyDecimal($producto->getOption('promotionbonus'))) : ?>
                                                <div class="line">
                                                    <div class="left">Coney Bonos Plus</div>
                                                    <div class="right">S/. <?php echo $producto->getOption('promotionbonus', true); ?></div>
                                                </div>
                                                <?php endif; ?>
                                                <?php if (\Common\Helpers\Util::noEmptyDecimal($producto->getOption('etickets'))) : ?>
                                                <div class="line">
                                                    <div class="left">Tickets</div>
                                                    <div class="right"><?php echo $producto->getOption('etickets'); ?></div>
                                                </div>
                                                <?php endif; ?>
                                            </div>
                                            <div class="link_show">
                                                <div class="watch_detail">Ver detalle</div>
                                                <div class="hidden_detail">Ocultar detalle</div>
                                            </div>
                                            <?php $partMonto = explode('.', $producto->getAmount(true)); ?>
                                            <div class="total">S/. <span><?php echo $partMonto[0]; ?></span>.<?php echo $partMonto[1]; ?> </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </div>

                        <input id="acepto" name="acepto" type="checkbox" class="" data-parsley-required="true" data-parsley-required-message="Debe aceptar los términos y condiciones del sitio"/>Declaro conocer y aceptar los <a target="_blank" href="<?php echo BASE_URL ?>terminos-condiciones" >Términos y condiciones</a> del sitio.

                        <div align="center" class="total_box">
                            <?php $montoTotal = empty($cartModel) ? '0.00' : $cartModel->getAmountCart(true); ?>
                            <?php $partMontoTotal = explode('.', $montoTotal); ?>
                            <h3>
                                <span>Pago total: </span>
                                <span class="medium">S/. </span>
                                <span class="large"><?php echo $partMontoTotal[0]; ?></span>
                                <span class="medium">.<?php echo $partMontoTotal[1]; ?></span>
                            </h3>
                            <input type="hidden" id="token_csrf" name="token_csrf" value="<?php echo $tokenCsrf; ?>">
                            <button id="btnPagar" class="btn btn_orange" type="submit">Pagar</button>
                            <a href="<?php echo BASE_URL ?>recargas" class="link_orange">Seguir comprando  </a>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        
    </div>
    <?php if (!empty($cartModel)) : ?>
    <?php $index = 0; ?>
    <?php foreach ($cartModel->getProductsCart() as $productos) : ?>
        <?php foreach ($productos as $producto) : ?>
            <?php $index++; ?>
            <div id="modal_watch_legal_<?php echo $index; ?>" class="modal_box modal_box_legal">
                  <div class="modal_content">
                    <h3>Importante: <span></span></h3>
                    <hr/>
                    <div class="text_box">
                      <p><?php echo $producto->getOption('legal'); ?></p>
                    </div>
                  </div>
            </div>
        <?php endforeach; ?>
    <?php endforeach; ?>
    <?php endif; ?>
    <div id="mask"></div>
</section>
</form>
<script type="text/javascript">
    /*$('#btnPagar').click(function(){
        $.ajax({
          type: "POST",
          url: baseUrl + 'carrito/pagar',
          data: $('#formPago').serialize(),
          dataType: 'json',
          success: function(response) {
            $('#token_csrf').val(response.token);
            if (response.success) {
                $('.error_message').hide();
                window.location.href = response.data.redirect;
            } else {
              $('#messageError').html(response.message);
              $('.error_message').show();
            }
          },
          error: function(XMLHttpRequest, textStatus, errorThrown) {
              $('#messageError').html('Lo sentimos, no se pudo completar el proceso, por favor inténtalo más tarde');
              $('.error_message').show();
          }
        });
    });*/

    $('#perfil_pago').change(function(){
        $.ajax({
          type: "POST",
          url: baseUrl + 'carrito/perfil-pago',
          data: {perfil_pago:$('#perfil_pago').val(), token_csrf:$('#token_csrf').val()},
          dataType: 'json',
          success: function(data) {
            $('#token_csrf').val(data.token);
            $('#fac_razon_social').val('');
            $('#fac_direccion_fiscal').val('');
            $('#fac_direccion_entrega_factura').val('');
            $('#ruc').val('');
            $('#distrito_id').val('');
            if (data.success) {
                $('#fac_razon_social').val(data.data.fac_razon_social);
                $('#fac_direccion_fiscal').val(data.data.fac_direccion_fiscal);
                $('#fac_direccion_entrega_factura').val(data.data.fac_direccion_entrega_factura);
                $('#ruc').val(data.data.documento_numero);
                $('#distrito_id').val(data.data.distrito_id);
            }
          },
          error: function(XMLHttpRequest, textStatus, errorThrown) {
          }
        });
    });
</script>