<section class="app_content recargas">
    <div class="box_center">
        <div class="app_box">
            <div class="menu right_active">
                <ul>
                    <li class="first"><a href="<?php echo BASE_URL; ?>beneficios">Beneficios</a></li>
                    <li><a href="<?php echo BASE_URL; ?>mis-tarjetas">Mis tarjetas</a></li>
                    <li class="last active"><a href="<?php echo BASE_URL; ?>recargas">Recargas</a></li>
                </ul>
            </div>
            <div class="purple_box">
                <p class="yellow_text small_text">Recarga de mis tarjetas</p>
                <div class="steps">
                    <div class="step active">1</div>
                    <div class="step active">2</div>
                </div>
                <a href="<?php echo BASE_URL ?>carrito" class="cart_box">
                    <span class="label">Items en el carrito:</span>
                    <div class="cart">
                        <span class="icon"></span>
                        <span class="number"><?php echo empty($cartModel) ? 0 : $cartModel->getQuantityCart(); ?></span>
                    </div>
                </a>
                <div class="pay_box_white">
                    <div class="left">
                        <h4>1. Datos del Pago</h4>
                        <p>Datos solicitados para la generación del comprobante</p>
                        <div class="error_message"><span class="icon"></span>
                            <p>Lo sentimos, no se pudo completar el proceso, por favor inténtelo más tarde.</p>
                        </div>
                        <div class="voucher">
                            <input type="radio" name="voucher_option" checked="checked" class="boleta"/>Boleta
                            <input type="radio" name="voucher_option" class="factura"/>Factura
                        </div>
                        <div class="content_boleta">
                            <div class="form_control">
                                <label for="">Nombre</label>
                                <input type="text" placeholder="Andrea"/>
                            </div>
                            <div class="form_control">
                                <label for="">Apellido paterno</label>
                                <input type="text" placeholder="Delgado"/>
                            </div>
                            <div class="form_control">
                                <label for="">Apellido materno</label>
                                <input type="text" placeholder="Delgado"/>
                            </div>
                            <div class="form_control">
                                <label for="">DNI/Pasaporte</label>
                                <input type="text" placeholder="12345678"/>
                            </div>
                        </div>
                        <div class="content_factura">
                            <div class="form_control">
                                <label for="">Perfil de pago</label>
                                <select name="">
                                    <option value="">Seleccione</option>
                                    <option value="">1</option>
                                </select>
                            </div>
                            <div class="form_control">
                                <label for="">Razón Social</label>
                                <input type="text"/>
                            </div>
                            <div class="form_control">
                                <label for="">RUC</label>
                                <input type="text"/>
                            </div>
                            <div class="form_control">
                                <label for="">Dirección fiscal</label>
                                <input type="text"/>
                            </div>
                            <div class="form_control">
                                <label for="">Dirección de entrega de factura</label>
                                <input type="text"/>
                            </div>
                            <div class="form_control">
                                <input type="checkbox"/>Misma dirección fiscal
                            </div>
                            <div class="form_control">
                                <label for="">Distrito</label>
                                <select name="">
                                    <option value="">Seleccione</option>
                                    <option value="">Lima</option>
                                    <option value="">Breña</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="right">
                        <h4>2. Seleccione el método de pago</h4>
                        <div class="credit_cards">
                            <div class="card pagoefectivo active"></div>
                            <div class="card visa"></div>
                            <div class="cards_option">
                                <input type="radio" name="metodo_pago" checked="checked" class="pe"/>
                                <input type="radio" name="metodo_pago" class="visa"/>
                            </div>
                        </div>
                        <h4>3. Confirma tu compra</h4>
                        <div class="items_cart">
                            <?php foreach ($cartModel->getProductsCart() as $productos) : ?>
                                <?php foreach ($productos as $producto) : ?>
                                    <div class="item">
                                        <div class="left">
                                            <img width="140" height="71" src="<?php echo $urlImg . '/' . $producto->getProductImage(); ?>" alt="<?php echo $producto->getProductName(); ?>"/>
                                        </div>
                                        <div class="right">
                                            <h5><?php echo $producto->getProductName(); ?><span>. </span>
                                                <span class="legal">Ver legal</span>
                                            </h5>
                                            <h4 class="item_title"><?php echo $producto->getProductName2(); ?></h4>
                                            <div class="card_type">
                                                <span>En:</span><span class="icon_card"></span>
                                                <span class="card_name"><?php echo $producto->getCategoryName(); ?></span>
                                                <span class="cant">Cantidad: <?php echo $producto->getQuantity(); ?></span>
                                            </div>
                                            <div class="detail">
                                                <div class="line">
                                                    <div class="left">Coney Bonus</div>
                                                    <div class="right">S/. <?php echo $producto->getOption('bonus', true); ?></div>
                                                </div>
                                                <div class="line">
                                                    <div class="left">Coney Bonus Plus</div>
                                                    <div class="right">S/. <?php echo $producto->getOption('promotionbonus', true); ?></div>
                                                </div>
                                                <div class="line">
                                                    <div class="left">Tickets</div>
                                                    <div class="right"><?php echo $producto->getOption('etickets'); ?></div>
                                                </div>
                                            </div>
                                            <div class="link_show">
                                                <div class="watch_detail">Ver detalle</div>
                                                <div class="hidden_detail">Ocultar detalle</div>
                                            </div>
                                            <?php $partMonto = explode('.', $producto->getAmount(true)); ?>
                                            <div class="total">S/. <span><?php echo $partMonto[0]; ?></span>.<?php echo $partMonto[1]; ?> </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </div>
                        <div align="center" class="total_box">
                            <?php $montoTotal = empty($cartModel) ? '0.00' : $cartModel->getAmountCart(true); ?>
                            <?php $partMontoTotal = explode('.', $montoTotal); ?>
                            <h3>
                                <span>Pago total: </span>
                                <span class="medium">S/. </span>
                                <span class="large"><?php echo $partMontoTotal[0]; ?></span>
                                <span class="medium">.<?php echo $partMontoTotal[1]; ?></span>
                            </h3>
                            <button class="btn btn_orange">Pagar</button>
                            <a href="<?php echo BASE_URL ?>recargas" class="link_orange">Seguir comprando  </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>