<?php $this->form->prepare(); ?>
<?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-inline isearch')); ?>
    <div class="box-body">
        <div class="form-group">
            <label class="control-label" for="email">Email</label>
            <?php echo $this->formElement($this->form->get('email')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="password">Password</label>
            <?php echo $this->formElement($this->form->get('password')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="token">Token</label>
            <?php echo $this->formElement($this->form->get('token')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="red">Red</label>
            <?php echo $this->formElement($this->form->get('red')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="estado">Estado</label>
            <?php echo $this->formElement($this->form->get('estado')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="imagen">Imagen</label>
            <?php echo $this->formElement($this->form->get('imagen')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="nombres">Nombres</label>
            <?php echo $this->formElement($this->form->get('nombres')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="paterno">Paterno</label>
            <?php echo $this->formElement($this->form->get('paterno')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="materno">Materno</label>
            <?php echo $this->formElement($this->form->get('materno')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="fecha_nac">Fecha_nac</label>
            <?php echo $this->formElement($this->form->get('fecha_nac')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="cod_pais">Cod_pais</label>
            <?php echo $this->formElement($this->form->get('cod_pais')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="cod_depa">Cod_depa</label>
            <?php echo $this->formElement($this->form->get('cod_depa')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="cod_prov">Cod_prov</label>
            <?php echo $this->formElement($this->form->get('cod_prov')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="cod_dist">Cod_dist</label>
            <?php echo $this->formElement($this->form->get('cod_dist')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="fecha_creacion">Fecha_creacion</label>
            <?php echo $this->formElement($this->form->get('fecha_creacion')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="fecha_edicion">Fecha_edicion</label>
            <?php echo $this->formElement($this->form->get('fecha_edicion')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Buscar</button>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>