<?php $this->form->prepare(); ?>
<?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-inline isearch')); ?>
    <div class="box-body">
        <div class="form-group">
            <label class="control-label" for="tipo">Buscar por </label>
            <?php echo $this->formElement($this->form->get('cmbFiltro')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($this->form->get('txtBuscar')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <button id="btnBuscar" class="btn btn-primary" type="submit">Buscar</button>
        </div>
        <br>
        <div class="form-group">
            <label class="control-label" for="tipo">Filtrar por :  Tipo Doc. </label>
            <?php echo $this->formElement($this->form->get('cmbTipoDoc')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="tipo"> Estado </label>
            <?php echo $this->formElement($this->form->get('cmbEstado')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="tipo"> Pais  </label>
            <?php echo $this->formElement($this->form->get('cmbPais')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="tipo"> Departamento  </label>
            <?php echo $this->formElement($this->form->get('cmbDepartamento')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="tipo"> Provincia  </label>
            <?php echo $this->formElement($this->form->get('cmbProvincia')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="tipo"> Distrito  </label>
            <?php echo $this->formElement($this->form->get('cmbDistrito')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="tipo"> Desde  </label>
            <?php echo $this->formElement($this->form->get('txtFechaIni')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="tipo"> Hasta  </label>
            <?php echo $this->formElement($this->form->get('txtFechaFin')->setAttribute('class', 'form-control')) ?>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>