<?php $this->form->prepare(); ?>
<div class="box">
    <div class="box-header with-border">
        <label>Usuario</label>
    </div>
    <?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-horizontal')); ?>
    <div class="box-body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="email">Email</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('email')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('email')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="password">Password</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('password')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('password')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="token">Token</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('token')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('token')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="red">Red</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('red')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('red')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="estado">Estado</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('estado')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('estado')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="imagen">Imagen</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('imagen')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('imagen')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="nombres">Nombres</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('nombres')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('nombres')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="paterno">Paterno</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('paterno')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('paterno')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="materno">Materno</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('materno')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('materno')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="fecha_nac">Fecha_nac</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('fecha_nac')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('fecha_nac')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="pais_id">Cod_pais</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('pais_id')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('pais_id')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="departamento_id">Cod_depa</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('departamento_id')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('departamento_id')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="provincia_id">Cod_prov</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('provincia_id')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('provincia_id')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="distrito_id">Cod_dist</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('distrito_id')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('distrito_id')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="fecha_creacion">Fecha_creacion</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('fecha_creacion')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('fecha_creacion')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="fecha_edicion">Fecha_edicion</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('fecha_edicion')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('fecha_edicion')); ?></span>
            </div>
        </div>
        <div class="box-footer">
            <a class="btn btn-default" href="<?php echo BASE_URL; ?>usuario/index">Regresar</a>
            <button class="btn btn-success" type="submit">Aceptar</button>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>