<?php $this->layout()->title = array('Usuario', 'Listado') ?>
<?php
$this->layout()->breadcrumb = array(
    array('url' => null, 'name' => 'Usuario'),
    array('url' => null, 'name' => 'Listado'),
);
?>

<div class="box">
    <div class="box-header with-border">
        <?php echo $this->partial('admin/usuario/_buscar.phtml', array('form' => $form)); ?>
    </div>
    <div class="box-body">
        <?php echo $this->showMessenger($this->flashMessenger()->getMessages()); ?>
        <a href="javascript:exportarExcel()" class="btn btn-success">Exportar</a>
        <hr class="separator">
        <table id="gridMain" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Email</th>
                    <th style="white-space:nowrap;">Nombres</th>
                    <th style="white-space:nowrap;">A. Paterno</th>
                    <th style="white-space:nowrap;">A. Materno</th>
                    <th style="white-space:nowrap;">Tipo Doc.</th>
                    <th style="white-space:nowrap;">Nro. Doc.</th>
                    <th>Pais</th>
                    <th>Departamento</th>
                    <th>Provincia</th>
                    <th>Distrito</th>
                    <th style="white-space:nowrap;">Fecha Registro</th>
                    <th>Estado</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($gridList as $row) : ?>
                    <tr>
                        <td ><?php echo $row['email'] ?></td>
                        <td><?php echo $row['nombres'] ?></td>
                        <td><?php echo $row['paterno'] ?></td>
                        <td><?php echo $row['materno'] ?></td>
                        <td><?php echo \Usuario\Model\Service\UsuarioService::getNombreTipoDocumento($row['di_tipo']); ?></td>
                        <td><?php echo $row['di_valor'] ?></td>
                        <td><?php echo $row['nombrePais'] ?></td>
                        <td><?php echo $row['nombreDepa'] ?></td>
                        <td><?php echo $row['nombreProv'] ?></td>
                        <td><?php echo $row['nombreDist'] ?></td>
                        <td><?php echo $row['fecha_creacion'] ?></td>
                        <td><?php echo \Usuario\Model\Service\UsuarioService::getNombreEstado($row['estado']); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<link  href="http://dev.recargas.coneypark.pe/s/front/datepicker/css/datepicker.css" rel="stylesheet"></link>
<link  href="http://dev.recargas.coneypark.pe/s/front/datepicker/css/bootstrap_.css" rel="stylesheet"></link>
<script src="/s/front/datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
         $('#gridMain').DataTable({
            "pageLength": 25,
            "paging": true,
            "lengthChange": true,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": true,
            "order": [[ 2, "desc" ]] ,
            columnDefs: [
                 { orderable: false, targets: [0,1,3,4,5,6,7,8,9,10] }
            ]
        });
        common.deleteRemote();

        $("#cmbDepartamento").on('change', function() {
            $("#formBuscar").submit();
        });

        $("#cmbProvincia").on('change', function() {
            $("#formBuscar").submit();
        });

        $("#cmbDistrito").on('change', function() {
            $("#formBuscar").submit();
        });

        $("#cmbTipoDoc").on('change', function() {
            $("#formBuscar").submit();
        });

        $("#cmbEstado").on('change', function() {
            $("#formBuscar").submit();
        });

        $("#txtFechaIni").datepicker({
            format: 'yyyy-mm-dd'
        }).on('changeDate', function(e){
            $("#formBuscar").submit();
        });

        $("#txtFechaFin").datepicker({
            format: 'yyyy-mm-dd'
        }).on('changeDate', function(e){
            $("#formBuscar").submit();
        });

    });

    function exportarExcel(){
        $("#formBuscar").attr("action", "<?php echo BASE_URL; ?>admin/usuario/exportar-excel");
        $("#formBuscar").submit();
        $("#formBuscar").attr("action", "<?php echo BASE_URL; ?>admin/usuario");
    }

</script>