<p class="yellow_text small_text">Recargas</p>
<div class="offers">
    <?php foreach ($rowRecargas as $key =>  $row) : ?>
        <?php if ($row['show'] == 'lleno') : ?>
            <div class="col_3">
                <div class="box_white">
                    <div class="image"><img src="<?php echo $urlImg . '/' . $row['imagen']; ?>" alt="<?php echo $row['titulo1']; ?>"/></div>
                    <p class="breadcrumb">
                        <?php echo $row['titulo1']; ?>
                        <a href="#modal_watch_legal" name="modal" class="watch_legal">Ver legal</a>
                        <span></span>
                    </p>
                    <p><?php echo $row['titulo2']; ?></p>
                    <div class="detail">
                        <?php if (\Common\Helpers\Util::noEmptyDecimal($row['emoney'])) : ?>
                        <div class="line">
                            <div class="left">Dinero</div>
                            <div class="right">S/. <?php echo \Common\Helpers\Util::formatDecimal($row['emoney']); ?></div>
                        </div>
                        <?php endif; ?>
                        <?php if (\Common\Helpers\Util::noEmptyDecimal($row['bonus'])) : ?>
                        <div class="line">
                            <div class="left">Coney Bonus</div>
                            <div class="right">S/. <?php echo \Common\Helpers\Util::formatDecimal($row['bonus']); ?></div>
                        </div>
                        <?php endif; ?>
                        <?php if (\Common\Helpers\Util::noEmptyDecimal($row['promotionbonus'])) : ?>
                        <div class="line">
                            <div class="left">Coney Bonus Plus</div>
                            <div class="right">S/. <?php echo \Common\Helpers\Util::formatDecimal($row['promotionbonus']); ?></div>
                        </div>
                        <?php endif; ?>
                        <?php if (\Common\Helpers\Util::noEmptyDecimal($row['etickets'])) : ?>
                        <div class="line">
                            <div class="left">Tickets</div>
                            <div class="right"><?php echo $row['etickets']; ?></div>
                        </div>
                        <?php endif; ?>
                        <?php if (\Common\Helpers\Util::noEmptyDecimal($row['gamepoints'])) : ?>
                        <div class="line">
                            <div class="left">Gamepoints</div>
                            <div class="right"><?php echo $row['gamepoints']; ?></div>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
                <?php $prefix = 'p' . $key; ?>
                <div class="cant_box" data-prefix="<?php echo $prefix; ?>">
                    <span class="less">-</span>
                    <?php $cantidad = isset($tarjetaProductos[$row['id']]) ? $tarjetaProductos[$row['id']]->getQuantity() : null; ?>
                    <input id="cantidad_<?php echo $prefix; ?>" type="text" placeholder="0" class="cant" value="<?php echo $cantidad; ?>"/>
                    <input id="id_<?php echo $prefix; ?>" type="hidden" value="<?php echo $row['id']; ?>"/>
                    <span class="more">+</span>
                </div>
            </div>
        <?php else : ?>
            <div class="col_3"></div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>