<!--FOOTER-->
<div class="bg_diagonal_footer"></div>
<footer>
	<span class="top"></span>
	<span class="logo_icon"></span>
	<img src="<?php echo URL_RESOURCES ?>front/dist/images/bottom.png" alt="" class="bg"/>
    <ul>
        <li><a href="http://coneypark.pe/contactos/">CONTACTO</a></li>
        <li><a href="http://coneypark.pe/preguntas-frecuentes/">PREGUNTAS FRECUENTES</a></li>
        <li><a href="">TÉRMINOS Y CONDICIONES</a></li>
    </ul>
    <div class="right_options mobile">
      <ul>
        <li><a href=""><span class="icon"><i class="icon-gold"></i></span><span class="text">CONEY CLUB</span></a></li>
        <li class="active"><a href="javascript:;"><span class="icon"><i class="icon-conexxion"></i></span><span class="text">RECARGAS</span></a></li>
        <li><a href=""><span class="icon"><i class="icon-pastel"></i></span><span class="text">CUMPLEAÑOS</span></a></li>
      </ul>
    </div>
</footer>
