<div class="right_options">
      <ul>
        <li><a href=""><span class="icon"><i class="icon-gold"></i></span><span class="text">CLIENTE GOLD</span></a></li>
        <li><a href=""><span class="icon"><i class="icon-conexxion"></i></span><span class="text">RECARGAS</span></a></li>
        <li><a href=""><span class="icon"><i class="icon-pastel"></i></span><span class="text">CUMPLEAÑOS</span></a></li>
      </ul>
    </div>