<div class="offers_box">
    <div class="col_3 left"><img src="<?php echo URL_RESOURCES ?>front/dist/images/promo1.png" alt=""/>
        <p>Por lanzamiento, recarga <strong>S/.100 </strong>y obten<strong>S/.50</strong>soles adicionales <strong>+ S/.30 </strong>en Coney Bonos</p>
    </div>
    <div class="col_3 left"><img src="<?php echo URL_RESOURCES ?>front/dist/images/promo2.png" alt=""/>
        <p>Por lanzamiento, recarga <strong>S/.100 </strong>y obten<strong>S/.50</strong>soles adicionales <strong>+ S/.30 </strong>en Coney Bonos</p>
    </div>
    <div class="col_3 right"><img src="<?php echo URL_RESOURCES ?>front/dist/images/promo3.png" alt=""/>
        <p>Por lanzamiento, recarga <strong>S/.100 </strong>y obten<strong>S/.50</strong>soles adicionales <strong>+ S/.30 </strong>en Coney Bonos</p>
    </div>
</div>