<!--HEADER-->
<header><img src="<?php echo URL_RESOURCES ?>front/dist/images/top.png" alt="" class="bg"/>
    <div class="box_center">
        <div class="social_icons"><a href=""><span class="fb"></span></a><a href=""><span class="in"></span></a></div>
        <nav>
            <ul>
                <li><a href="">
                        <div class="icon"><span class="icon_local"></span></div><span class="text">LOCALES</span></a></li>
                <li><a href="">
                        <div class="icon"><span class="icon_offers"></span></div><span class="text">PROMOCIONES</span></a></li>
                <li><a href="">
                        <div class="icon"><span class="icon_atraction"></span></div><span class="text">NUESTRAS ATRACCIONES</span></a></li>
                <li class="logo"><a href=""><img src="<?php echo URL_RESOURCES ?>front/dist/images/logo.png" alt="Coney Park"/></a></li>
                <li><a href="">
                        <div class="icon"><span class="icon_sale"></span></div><span class="text">VENTAS CORPORATIVAS</span></a></li>
                <li><a href="">
                        <div class="icon"><span class="icon_card"></span></div><span class="text">TARJETA CONEXIÓN</span></a></li>
                <li><a href="">
                <div class="icon"><span class="icon_gold"></span></div><span class="text">CLIENTE GOLD</span></a></li>
            </ul>
        </nav>
    </div>
</header>