<!--HEADER-->
<header><img src="<?php echo URL_RESOURCES ?>front/dist/images/top.png" alt="" class="bg"/>
    <div class="box_center">
        <div class="social_icons"><a target="_blank" href="https://www.facebook.com/coneyparkperu"><span class="fb"></span></a><a target="_blank" href="https://www.instagram.com/coneyparkperu/"><span class="in"></span></a></div>
        <div class="user_option">
            <?php if (empty($data)) : ?>
                <div class="user_outside">
                    <a href="<?php echo BASE_URL ?>login"><span class="text">Inicia Sesión</span><span class="icon"></span></a>
                </div>
            <?php else : ?>
                <div class="user_inside">
                    <ul>
                        <li><a href="<?php echo BASE_URL ?>carrito"><span class="icon_cart"></span><span class="icon_counter cart_count_header"><?php echo $totalCarrito; ?></span></a></li>
                        <li>
                            <a href="#" class="user_account">
                                <span class="text"><?php echo $data['nombres'] ?></span>
                                <?php $imagen = !empty($data['imagen']) ? $urlImg . '/' . $data['imagen'] : $urlImg . '/user-web-default.png'; ?>

                                <span class="user_image"><img src="<?php echo $imagen; ?>" onerror="this.src='<?php echo $urlImg . '/user-web-default.png'; ?>';" alt="<?php echo $data['nombres'] ?>"/></span>
                                
                                <span class="arrow_bottom"></span>
                            </a>
                            <div class="menu_options">
                                <a href="<?php echo BASE_URL ?>mis-datos" class="logout">Mis datos</a>
                                <a href="<?php echo BASE_URL ?>login/logout" class="logout">Cerrar sesión</a>
                            </div>
                        </li>
                    </ul>
                </div>
            <?php endif; ?>
        </div>
        
        <div class="user_option_mobile">
            <ul>
                <?php if (!empty($data)) : ?>
                <li>
                    <?php $imagen = !empty($data['imagen']) ? $urlImg . '/' . $data['imagen'] : $urlImg . '/user-web-default.png'; ?>
                    <span class="user_icon">
                        <img src="<?php echo $imagen; ?>" onerror="this.src='<?php echo $urlImg . '/user-web-default.png'; ?>';" alt="<?php echo $data['nombres'] ?>">
                    </span>
                    <div class="menu_options">
                        <a href="<?php echo BASE_URL ?>mis-datos" class="logout">Mis datos</a>
                        <a href="<?php echo BASE_URL ?>login/logout" class="logout">Cerrar sesión</a>
                    </div>
                </li>
                <li>
                    <a href="<?php echo BASE_URL ?>carrito">
                    <span class="cart_number cart_count_header"><?php echo $totalCarrito; ?></span>
                    <span class="cart_icon"></span>
                    </a>
                </li>
                <?php else : ?>
                    <li>
                        <a href="<?php echo BASE_URL ?>login"><span class="icon"></span></a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
        

        
        <nav>
            <ul>
                <li>
                    <a href="http://coneypark.pe/locales/">
                        <div class="icon"><i class="icon-locales"></i></div><p class="text">LOCALES</p>
                    </a>
                </li>
                <li>
                    <a href="http://coneypark.pe/promociones/">
                        <div class="icon"><i class="icon-promociones"></i></div><p class="text">PROMOCIONES</p>
                    </a>
                </li>
                <li>
                    <a href="http://coneypark.pe/juegos/">
                        <div class="icon"><i class="icon-consola"></i></div><p class="text">NUESTRAS ATRACCIONES</p>
                    </a>
                </li>
                <li class="logo">
                    <a href="http://coneypark.pe/">
                        <img src="<?php echo URL_RESOURCES ?>front/dist/images/logo.png" alt="Coney Park"/>
                    </a>
                </li>
                <li>
                    <a href="http://coneypark.pe/ventas-corporativas/">
                        <div class="icon"><i class="icon-corporativa"></i></div><p class="text">VENTAS CORPORATIVAS</p>
                    </a>
                </li>
                <li>
                    <a href="http://coneypark.pe/preguntas-frecuentes/">
                        <div class="icon"><i class="icon-conexxion"></i></div>
                        <p class="text">PREGUNTAS FRECUENTES</p>
                    </a>
                </li>
                <li>
                    <a href="http://coneypark.pe/coney-club/">
                        <div class="icon"><i class="icon-gold"></i></div>
                        <p class="text">CONEY CLUB</p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="menu_icon">
        <i class="icon-menu"></i>
    </div>
    <div class="bg_diagonal"></div>
</header>
<div id="menuMovil" class="list-m movil">
    <div class="list-m-inner">
        <div class="box-mmenu">
            <div class="list-menu">
                <div class="row-fluid">
                    <div class="span6">
                        <ul class="menu-nav">
                            <li><a href="http://coneypark.pe/locales"><i class="icon-locales"></i> <span>Locales</span></a></li>
                            <li><a href="http://coneypark.pe/promociones"><i class="icon-promociones"></i> <span>Promociones</span></a></li>
                            <li><a href="http://coneypark.pe/juegos"><i class="icon-consola"></i> <span>Nuestras<br> Atracciones</span></a></li>
                        </ul>
                    </div>
                    <div class="span6">
                        <ul class="menu-nav">
                            <li><a href="http://coneypark.pe/ventas-corporativas"><i class="icon-corporativa"></i> <span>Ventas<br> Corporativas</span></a></li>
                            <li><a href="http://coneypark.pe/preguntas-frecuentes"><i class="icon-conexxion"></i> <span>Preguntas<br> Frecuentes</span></a></li>
                            <li><a href="http://coneypark.pe/coney-club"><i class="icon-gold"></i> <span>Coney Club</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="list-sub-menu">
                <div class="row-fluid">
                    <div class="span6">
                        <a href="http://coneypark.pe/empresa">LA EMPRESA</a>
                    </div>
                    <div class="span6">
                        <a href="http://coneypark.pe/contactos">CONTÁCTANOS</a>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <a target="_blank" href="http://www.bumeran.com.pe/lima/empleos-busqueda-coney-park.html">TRABAJA CON NOSOTROS</a>
                    </div>
                    <div class="span6">
                        <a target="_blank" href="http://23.96.201.140/portal">INTRANET</a>
                    </div>
                </div>
            </div>

            <div class="social-media">
                <span>Únete</span>
                <ul class="social-list">
                    <li><a href="https://www.facebook.com/coneyparkperu"><img alt="Facebook" src="http://coneypark.pe/wp-content/themes/coneytheme/img/icon_m_fb.png"></a></li>
                    <li><a href="https://www.instagram.com/coneyparkperu"><img alt="Instagram" src="http://coneypark.pe/wp-content/themes/coneytheme/img/icon_m_ins.png"></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>