<?php $this->form->prepare(); ?>
<div class="box">
    <div class="box-header with-border">
        <label>Paquete</label>
    </div>
    <?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-horizontal')); ?>
    <div class="box-body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="titulo1">Titulo 1 <span>*</span></label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('titulo1')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('titulo1')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="titulo2">Titulo 2</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('titulo2')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('titulo2')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="importe_minimo">Importe Mínimo <span>*</span></label>
            <div class="col-sm-8">
                <label><?php echo $this->form->get('importe_minimo')->getValue(); ?></label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="importe_emoney">Importe Emoney <span>*</span></label>
            <div class="col-sm-8">
                <label><?php echo $this->form->get('importe_emoney')->getValue(); ?></label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="importe_bonus">Importe Bonus <span>*</span></label>
            <div class="col-sm-8">
                <label><?php echo $this->form->get('importe_bonus')->getValue(); ?></label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="tickets">Tickets <span>*</span></label>
            <div class="col-sm-8">
                <label><?php echo $this->form->get('tickets')->getValue(); ?></label>
            </div>
        </div>
        <div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="imagen">Imagen <span>*</span></label>

                <div class="col-sm-10">
                    <?php echo $this->formElement($this->form->get('imagen')); ?>
                    <span class="error"><?php echo $this->formElementerrors($form->get('imagen')); ?></span>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <a class="btn btn-default" href="<?php echo BASE_URL; ?>paquete/paquete/index">Regresar</a>
            <button class="btn btn-success" type="submit">Aceptar</button>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>