
<html>
<head>
    <title>Coney Park - Políticas de privacidad</title>
    <meta name="description" content="Políticas de privacidad"/>
    <link rel="stylesheet" href="<?php echo URL_RESOURCES ?>front/dist/css/normalize.css?v=<?php echo VERSION_STATICO; ?>"/>
    <link rel="stylesheet" href="<?php echo URL_RESOURCES ?>front/dist/css/style.css?v=<?php echo VERSION_STATICO; ?>"/>
</head>
<body class="body_informativo">
<div class="wrapper">
    <header class="header_informativo">
        <div class="box_center"><a href="<?php echo BASE_URL ?>" class="logo"><img src="<?php echo URL_RESOURCES ?>front/dist/images/logo.png" alt=""/></a>
<!--            <div class="user_option">-->
<!--                <div class="user_outside"><a href=""> <span class="text">Inicia Sesión</span><span class="icon"></span></a></div>-->
<!--                <div class="user_inside">-->
<!--                    <ul>-->
<!--                        <li><a href=""><span class="icon_cart"></span><span class="icon_counter">3</span></a></li>-->
<!--                        <li><a href="" class="user_account"> <span class="text">Andrea </span><span class="user_image"><img src="" alt=""/></span><span class="arrow_bottom"></span></a><a href="" class="logout">Salir</a></li>-->
<!--                    </ul>-->
<!--                </div>-->
<!--            </div>-->
        </div>
    </header>
    <section class="section_informativo">
        <div class="box_center">
            <div class="breadcrumb"><a href="<?php echo BASE_URL ?>beneficios">Portada</a><span>> </span><span>Políticas y tratamientos de datos personales</span></div>
            <div class="content">
                <h2 class="purple">Políticas y tratamientos de datos personales</h2>
                <p>Gracias por acceder a la página web <a href="">www.coneypark.pe</a>&nbsp;(el “Sitio”) operada por ATRACCIONES CONEY ISLAND S.A.C. ÊNosotros respetamos su privacidad y su información personal. La presente política forma parte de uso del Sitio.</p>
                <p>Nuestra Política de Privacidad explica cómo recolectamos, utilizamos y (bajo ciertas condiciones) divulgamos su información personal. Esta Política de Privacidad también explica las medidas que hemos tomado para asegurar su información personal. Por último, esta política de privacidad explica los procedimientos que seguimos frente a la recopilación, uso y divulgación de su información personal.</p>
                <p>La protección de datos ...</p>
                <h3 class="purple">Cookies</h3>
                <p>Para efectos de la presente política, las palabras que a continuación se definen tendrán el significado asignado en este capítulo, sea que se escriban en minúsculas o no en mayúsculas, o que se encuentren en plural o singular</p>
                <h3 class="purple">Definiciones</h3>
                <p><span class="purple">a. Autorización: </span><span>Consentimiento previo, expreso e informado del titular para llevar a cabo el Tratamiento de Datos Personales.</span></p>
                <p><span class="purple">b. Aviso de Privacidad: </span><span>Documento físico, electrónico o en cualquier otro formato, generado por el Responsable del Tratamiento, que es puesto a disposición del Titular para el Tratamiento de sus Datos Personales, el cual comunica al Titular la información relativa a la existencia de las políticas de tratamiento de información que le serán aplicables, la forma de acceder a las mismas y las características del Tratamiento que se pretende dar a los datos personales.</span></p>
                <h3 class="purple">II. Normas y criterios de aplicación</h3>
                <h3 class="purple">01. Principios generales para el tratamiento de datos personales </h3>
                <p>En el Tratamiento de Datos Personales se cumplirá con los siguientes principios:</p>
                <p><span class="purple">Principio de finalidad: </span><span>El Tratamiento de Datos Personales debe obedecer a una finalidad legítima que se informará al Titular.</span></p>
                <p><span class="purple">Principio de libertad: </span><span>El Tratamiento de Datos Personales sólo puede ejercerse con el consentimiento, previo, expreso e informado del Titular. Los Datos Personales no podrán ser obtenidos o divulgados sin previa autorización, o en ausencia de mandato legal o judicial que releve el consentimiento del Titular.</span></p>
            </div>
        </div>
    </section>
    <!--FOOTER-->
    <div class="bg_diagonal_footer"></div>
    <footer>
        <div class="top"></div><span class="logo_icon"></span><img src="<?php echo URL_RESOURCES ?>front/dist/images/bottom.png" alt="" class="bg"/>
        <ul>
            <li><a href="http://coneypark.pe/contactos/">CONTACTO</a></li>
            <li><a href="http://coneypark.pe/preguntas-frecuentes/">PREGUNTAS FRECUENTES</a></li>
            <li><a href="<?php echo BASE_URL . 'terminos-condiciones' ?>">TÉRMINOS Y CONDICIONES</a></li>
        </ul>
        <div class="right_options mobile">
            <ul>
                <li><a href="<?php echo BASE_URL . 'registrate' ?>"><span class="icon"><i class="icon-gold"></i></span><span class="text">CONEY CLUB</span></a></li>
                <li class="active"><a href="<?php echo BASE_URL . 'recargas' ?>"><span class="icon"><i class="icon-conexxion"></i></span><span class="text">RECARGAS</span></a></li>
                <li><a href="http://coneypark.pe/cumpleanos/"><span class="icon"><i class="icon-pastel"></i></span><span class="text">CUMPLEAÑOS</span></a></li>
            </ul>
        </div>
    </footer>
</div>
<!--JS-->

<script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
<script>var baseUrl = '<?php echo BASE_URL; ?>';</script>
<script src="<?php echo URL_RESOURCES ?>front/dist/js/plugins/parsley.min.js"></script>
<script src="<?php echo URL_RESOURCES ?>front/dist/js/app.index.js?v=<?php echo VERSION_STATICO; ?>"></script>

</body>
</html>