<?php $this->form->prepare(); ?>
<?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-inline isearch')); ?>
    <div class="box-body">
        <div class="form-group">
            <label class="control-label" for="email">Email</label>
            <?php echo $this->formElement($this->form->get('email')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="password">Password</label>
            <?php echo $this->formElement($this->form->get('password')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="nombres">Nombres</label>
            <?php echo $this->formElement($this->form->get('nombres')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="paterno">Paterno</label>
            <?php echo $this->formElement($this->form->get('paterno')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="materno">Materno</label>
            <?php echo $this->formElement($this->form->get('materno')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Buscar</button>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>