<?php $this->layout()->title = array('Usuario', 'Listado') ?>
<?php
$this->layout()->breadcrumb = array(
    array('url' => null, 'name' => 'Usuario'),
    array('url' => null, 'name' => 'Listado'),
);
?>

<div class="box">
    <div class="box-header with-border">
        <?php echo $this->partial('usuario/usuario/_buscar.phtml', array('form' => $form)); ?>
    </div>
    <div class="box-body">
        <?php echo $this->showMessenger($this->flashMessenger()->getMessages()); ?>
        <a href="<?php echo BASE_URL; ?>usuario/usuario/crear" class="btn btn-success">Excel</a>
        <hr class="separator">
        <table id="gridMain" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Nombres</th>
                    <th>A. Paterno</th>
                    <th>A. Materno</th>
                    <th>Tipo Doc.</th>
                    <th>Nro. Doc,</th>
                    <th>Pais</th>
                    <th>Departamento</th>
                    <th>Provincia</th>
                    <th>Distrito</th>
                    <th>Estado</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($gridList as $row) : ?>
                    <tr>
                        <td><?php echo $row['email'] ?></td>
                        <td><?php echo $row['nombres'] ?></td>
                        <td><?php echo $row['paterno'] ?></td>
                        <td><?php echo $row['materno'] ?></td>
                        <td><?php echo $row['di_tipo'] ?></td>
                        <td><?php echo $row['di_valor'] ?></td>
                        <td><?php echo $row['nombrePais'] ?></td>
                        <td><?php echo $row['nombreDepa'] ?></td>
                        <td><?php echo $row['nombreProv'] ?></td>
                        <td><?php echo $row['nombreDist'] ?></td>
                        <td><?php echo $row['estado'] ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#gridMain').DataTable({
            "pageLength": 25,
            "paging": true,
            "lengthChange": true,
            "searching": false,
            "ordering": false,
            "info": true,
            "autoWidth": true
        });
        common.deleteRemote();
    });
</script>