<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Admin | Coney park</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.5 -->
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte/bootstrap/css/bootstrap.min.css?v=<?php echo VERSION; ?>">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte-ext/font-awesome-4.5.0/css/font-awesome.min.css?v=<?php echo VERSION; ?>">
        <!-- Ionicons -->
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte-ext/ionicons-2.0.1/css/ionicons.min.css?v=<?php echo VERSION; ?>">

        <!-- DataTables -->
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/datatables/dataTables.bootstrap.css">
    
        <!-- jvectormap -->
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.css?v=<?php echo VERSION; ?>">
        <!-- Theme style -->
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte/dist/css/AdminLTE.min.css?v=<?php echo VERSION; ?>">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte/dist/css/skins/_all-skins.min.css?v=<?php echo VERSION; ?>">
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/css/common.css?v=<?php echo VERSION; ?>">

        <!-- jQuery 2.1.4 -->
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/jQuery/jQuery-2.1.4.min.js?v=<?php echo VERSION; ?>"></script>
        
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="hold-transition skin-red sidebar-mini">
        <div class="wrapper">
            
            
            <?php echo $this->header(); ?>
            <?php echo $this->sidebar(); ?>

            <div class="content-wrapper">
                <section class="content-header">
                    <?php echo $this->breadcrumb($this->layout()); ?>
                </section>

                <section class="content">
                    <?php echo $this->content; ?>
                </section>
            </div>
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 1.0.0
                </div>
                <strong>Copyright &copy; 2016 Coney Park</a>.</strong> All rights reserved.
            </footer>
        </div>

        
        <!-- Bootstrap 3.3.5 -->
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/bootstrap/js/bootstrap.min.js?v=<?php echo VERSION; ?>"></script>
        <!-- FastClick -->
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/fastclick/fastclick.min.js?v=<?php echo VERSION; ?>"></script>
        <!-- AdminLTE App -->
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/dist/js/app.min.js?v=<?php echo VERSION; ?>"></script>
        <!-- Sparkline -->
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/sparkline/jquery.sparkline.min.js?v=<?php echo VERSION; ?>"></script>
        <!-- jvectormap -->
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js?v=<?php echo VERSION; ?>"></script>
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js?v=<?php echo VERSION; ?>"></script>
        <!-- SlimScroll 1.3.0 -->
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/slimScroll/jquery.slimscroll.min.js?v=<?php echo VERSION; ?>"></script>
        <!-- ChartJS 1.0.1 -->
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/chartjs/Chart.min.js?v=<?php echo VERSION; ?>"></script>
        
        <!-- DataTables -->
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/datatables/dataTables.bootstrap.min.js"></script>
        <script src="<?php echo URL_RESOURCES; ?>b/js/common.js"></script>
    </body>
</html>
