<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Login | Coney park</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.5 -->
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte/bootstrap/css/bootstrap.min.css?v=<?php echo VERSION; ?>">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte-ext/font-awesome-4.5.0/css/font-awesome.min.css?v=<?php echo VERSION; ?>">
        <!-- Ionicons -->
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte-ext/ionicons-2.0.1/css/ionicons.min.css?v=<?php echo VERSION; ?>">

        <!-- Theme style -->
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte/dist/css/AdminLTE.min.css?v=<?php echo VERSION; ?>">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte/dist/css/skins/_all-skins.min.css?v=<?php echo VERSION; ?>">
        <link rel="stylesheet" href="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/iCheck/square/blue.css?v=<?php echo VERSION; ?>">
        <!-- jQuery 2.1.4 -->
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/jQuery/jQuery-2.1.4.min.js?v=<?php echo VERSION; ?>"></script>
        
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="hold-transition login-page">
        <div class="login-box">
            <?php echo $this->content; ?>
        </div>
    
        <!-- Bootstrap 3.3.5 -->
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/bootstrap/js/bootstrap.min.js?v=<?php echo VERSION; ?>"></script>
        <!-- iCheck -->
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/iCheck/icheck.min.js?v=<?php echo VERSION; ?>"></script>
        <script>
          $(function () {
            $('input').iCheck({
              checkboxClass: 'icheckbox_square-blue',
              radioClass: 'iradio_square-blue',
              increaseArea: '20%' // optional
            });
          });
        </script>
    </body>
</html>
