<?php $form = $this->form->prepare(); ?>

<div class="login-box">
    <div class="login-logo">
        <a href="<?php echo BASE_URL ?>admin/login"><b>Admin </b>Coney Park</a>
    </div>
    <div class="login-box-body">
        <p class="login-box-msg">Ingrese Email y Password</p>
        <?php $flashMessage = $this->flashMessenger()->getMessages(); ?>
        <?php if (count($flashMessage) > 0) : ?>
        <div class="row">
            <ul>
                <?php foreach ($flashMessage as $msg) :?>
                    <?php foreach ($msg as $type => $message) : ?>
                        <li><span class="<?php echo $type; ?>"><?php echo $message; ?></span></li>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>

        <?php echo $this->form()->openTag($form); ?>
            <div class="form-group has-feedback">
                <?php echo $this->formInput($form->get('username')); ?>
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                <span class="error"><?php echo $this->formElementerrors($form->get('username')); ?></span>
            </div>
            <div class="form-group has-feedback">
                <?php echo $this->formInput($form->get('password')); ?>
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                <span class="error"><?php echo $this->formElementerrors($form->get('password')); ?></span>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <?php echo $this->formRow($form->get('token_csrf')); ?>
                    <?php echo $this->formInput($form->get('aceptar')); ?>
                </div>
            </div>
        <?php echo $this->form()->closeTag(); ?>

        <a href="#">Recuperar mi password</a><br>
    </div>
</div>