<?php $form = $this->form->prepare(); ?>

<div class="login-box">
    <div class="login-logo">
        <a href="<?php echo BASE_URL ?>admin/modificar-password"><b>Admin </b>Coney Park</a>
    </div>
    <div class="login-box-body">
        <p class="login-box-msg">Modificar Password</p>
        <?php $flashMessage = $this->flashMessenger()->getMessages(); ?>
        <?php if (count($flashMessage) > 0) : ?>
        <div class="row">
            <ul>
                <?php foreach ($flashMessage as $msg) :?>
                    <?php foreach ($msg as $type => $message) : ?>
                        <li><span class="<?php echo $type; ?>"><?php echo $message; ?></span></li>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>

        <?php echo $this->form()->openTag($form); ?>
            <div class="form-group has-feedback">
                <?php echo $this->formInput($form->get('password')); ?>
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                <span class="error"><?php echo $this->formElementerrors($form->get('password')); ?></span>
            </div>
            <div class="form-group has-feedback">
                <?php echo $this->formInput($form->get('password_repeat')); ?>
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                <span class="error"><?php echo $this->formElementerrors($form->get('password_repeat')); ?></span>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <?php echo $this->formElement($this->form->get('codigo')); ?>
                    <?php echo $this->formRow($form->get('token_csrf')); ?>
                    <?php echo $this->formInput($form->get('aceptar')); ?>
                </div>
            </div>
        <?php echo $this->form()->closeTag(); ?>
        <br>
        <a href="<?php echo BASE_URL; ?>admin/login">Login</a><br>
    </div>
</div>