<?php $form = $this->form->prepare(); ?>

<div class="login-box">
    <div class="login-logo">
        <a href="<?php echo BASE_URL ?>admin/recuperar-password"><b>Admin </b>Coney Park</a>
    </div>
    <div class="login-box-body">
        <p class="login-box-msg">Olvide mi Password</p>
        <?php $flashMessage = $this->flashMessenger()->getMessages(); ?>
        <?php if (count($flashMessage) > 0) : ?>
        <div class="row">
            <?php foreach ($flashMessage as $msg) :?>
                <?php foreach ($msg as $type => $message) : ?>
                    <span class="<?php echo $type; ?>"><ul><li><?php echo $message; ?></li></ul></span>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>

        <?php echo $this->form()->openTag($form); ?>
            <div class="form-group has-feedback">
                <?php echo $this->formInput($form->get('email')); ?>
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                <span class="error"><?php echo $this->formElementerrors($form->get('email')); ?></span>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <?php echo $this->formRow($form->get('token_csrf')); ?>
                    <?php echo $this->formInput($form->get('aceptar')); ?>
                </div>
            </div>
        <?php echo $this->form()->closeTag(); ?>
        <br>
        <a href="<?php echo BASE_URL; ?>admin/login">Login</a><br>
    </div>
</div>