<?php $this->form->prepare(); ?>
<section>
    <div class="box_center">
        <div class="welcome_box">
            <div class="yellow_box">Completa tu registro</div>
            <div class="purple_box">
                <div class="error_message hide"><span class="icon"></span><span class="text">Lo sentimos, no se pudo completar el proceso, por favor inténtalo mas tarde</span></div>
                <?php echo $this->form()->openTag($this->form->setAttribute('class', 'signin_form')); ?>
                <?php  $this->formElementerrors()->setMessageOpenFormat('<ul class="parsley-errors-list filled"><li class="parsley-required">')->setMessageCloseString('</li></ul>'); ?>
                    <h3>Tus datos de cuenta</h3>
                    <div class="content_form">
                        <div class="form_control">
                            <label class="left" for="email">Correo</label>
                            <?php $disabledCss = ($disabledEmail) ? 'disabled-email' : ''; ?>
                            <?php echo $this->formElement($this->form->get('email')->setAttributes(array(
                                'class' => 'right ' . $disabledCss,
                            ))) ?>
                            <?php echo $this->formElementerrors($form->get('email')); ?>
                        </div>
                        <div class="form_control">
                            <label class="left" for="password">Contraseña</label>
                            <?php echo $this->formElement($this->form->get('password')->setAttributes(array(
                                'class' => 'right',
                            ))) ?>
                            <?php echo $this->formElementerrors($form->get('password')); ?>
                        </div>
                        <div class="form_control">
                            <label class="left" for="password_repeat">Repetir contraseña</label>
                            <?php echo $this->formElement($this->form->get('password_repeat')->setAttributes(array(
                                'class' => 'right',
                            ))) ?>
                            <?php echo $this->formElementerrors($form->get('password_repeat')); ?>
                        </div>
                    </div>
                    <hr/>
                    <h3>Tus datos personales</h3>
                    <div class="content_form">
                        <div class="form_control">
                            <label class="left" for="nombres">Nombre</label>
                            <?php echo $this->formElement($this->form->get('nombres')->setAttributes(array(
                                'class' => 'right',
                            ))) ?>
                            <?php echo $this->formElementerrors($form->get('nombres')); ?>
                        </div>
                        <div class="form_control">
                            <label class="left" for="paterno">Apellido paterno</label>
                            <?php echo $this->formElement($this->form->get('paterno')->setAttributes(array(
                                'class' => 'right',
                            ))) ?>
                            <?php echo $this->formElementerrors($form->get('paterno')); ?>
                        </div>
                        <div class="form_control">
                            <label class="left" for="materno">Apellido materno</label>
                            <?php echo $this->formElement($this->form->get('materno')->setAttributes(array(
                                'class' => 'right',
                            ))) ?>
                            <?php echo $this->formElementerrors($form->get('materno')); ?>
                        </div>
                        <div class="form_control">
                            <label class="left" for="di_valor">Documento de identidad</label>
                            <div class="right">
                                <?php echo $this->formElement($this->form->get('di_tipo')->setAttributes(array(
                                    'class' => '',
                                ))) ?>
                                
                                <?php echo $this->formElement($this->form->get('di_valor')->setAttributes(array(
                                    'class' => '',
                                    'placeholder' => 'Nro de documento',
                                ))) ?>
                                <?php echo $this->formElementerrors($form->get('di_valor')); ?>
                            </div>
                        </div>
                        <div class="form_control">
                            <label class="left" for="cod_pais">País</label>
                            <?php echo $this->formElement($this->form->get('cod_pais')->setAttributes(array(
                                'class' => 'right',
                            ))) ?>
                            <?php echo $this->formElementerrors($form->get('cod_pais')); ?>
                        </div>
                        <div class="form_control">
                            <label class="left" for="cod_depa">Departamento</label>
                            <?php echo $this->formElement($this->form->get('cod_depa')->setAttributes(array(
                                'class' => 'right',
                            ))) ?>
                            <?php echo $this->formElementerrors($form->get('cod_depa')); ?>
                        </div>
                        <div class="form_control">
                            <label class="left" for="cod_dist">Distrito</label>
                            <?php echo $this->formElement($this->form->get('cod_dist')->setAttributes(array(
                                'class' => 'right',
                            ))) ?>
                            <?php echo $this->formElementerrors($form->get('cod_dist')); ?>
                        </div>
                        <div class="form_control">
                            <label class="left">Fecha de nacimiento</label>
                            <div class="right">
                                <?php echo $this->formElement($this->form->get('dia')->setAttributes(array(
                                    'class' => '',
                                ))) ?>
                                <?php echo $this->formElement($this->form->get('mes')->setAttributes(array(
                                    'class' => '',
                                ))) ?>
                                <?php echo $this->formElement($this->form->get('anio')->setAttributes(array(
                                    'class' => '',
                                ))) ?>
                                <?php echo $this->formElementerrors($form->get('dia')); ?>
                            </div>
                        </div>
                        <div class="form_control">
                            <div class="right">
                                <?php echo $this->formRow($form->get('token_csrf')); ?>
                                <button type="submit" class="btn btn_orange btn_save_signin">Registrarme</button>
                            </div>
                        </div>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
                <hr/>
                <div class="login_link"><a href="<?php echo BASE_URL ?>login">Ya tengo una cuenta en Coney Park<span></span></a></div>
            </div>
        </div>
        <div id="modal_response_signin" class="modal_box" data-open="<?php echo $openPopapConfRegistro; ?>">
          <div class="modal_content modal_recovery_content"><span class="icon_logo"></span>
            <?php echo $mensajeRegistro; ?>
            <a id="btn_recovery" href="#modal_recovery_response" name="modal" class="btn btn_orange">Aceptar</a>
          </div>
        </div>
        <div id="mask"></div>
    </div>
</section>
<script type="text/javascript">
    var ubigeo = {
        loadDepartameto:function(){
            $.ajax({
                type: "GET",
                url: '<?php echo BASE_URL; ?>application/ubigeo/departamento',
                data:{cod_pais:$('#cod_pais').val()},
                dataType: 'json',
                success: function(data){
                    var htmlDdl = '<option value="">- Seleccione -</option>';
                    for (var key in data) {
                        htmlDdl = htmlDdl+'<option value="'+key+'">'+data[key]+'</option>';
                    }
                    $('#cod_depa').html(htmlDdl);
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) { 
                }
            });
        },
        loadDistrito:function(){
            $.ajax({
                type: "GET",
                url: '<?php echo BASE_URL; ?>application/ubigeo/distrito',
                data:{cod_pais:$('#cod_pais').val(), cod_depa:$('#cod_depa').val()},
                dataType: 'json',
                success: function(data){
                    var htmlDdl = '<option value="">- Seleccione -</option>';
                    for (var key in data) {
                        htmlDdl = htmlDdl+'<option value="'+key+'">'+data[key]+'</option>';
                    }
                    $('#cod_dist').html(htmlDdl);
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) { 
                }
            });
        }
    };
    
    $(document).ready(function(){
        $('#cod_pais').change(function(){ubigeo.loadDepartameto();});
        $('#cod_depa').change(function(){ubigeo.loadDistrito();});
    });
</script>