<section>
    <div class="box_center">
        <div class="welcome_box">
            <?php echo $this->sectionContenido(Cms\Model\Service\ContenidoService::SECCION_INICIO_REGISTRO); ?>
<!--            <h2>¡Bienvenido a <span>Coney Club </span>recargas virtuales!</h2>-->
<!--            <h3>¡Un club creado para todos aquellos que buscan <span>más diversión </span>por mucho menos!</h3>-->
<!--            <p>Ahora podrás hacer tus recargas <strong>sin necesidad de hacer colas, </strong>además podrás gozar de <strong>muchos beneficios</strong></p>-->
            <div class="yellow_box">Regístrate</div>
            <div class="purple_box">
                <div class="content">
                    <div class="left">
                        <p>Usando tus redes sociales</p>
                        <button class="btn btn_fb" data-href="<?php echo BASE_URL; ?>login/validate-social/facebook"><span class="icon"></span><span class="text">Facebook</span></button>
                        <button class="btn btn_tw" data-href="<?php echo BASE_URL; ?>login/validate-social/twitter"><span class="icon"></span><span class="text">Twitter</span></button>
                    </div>
                    <span class="or_icon register"></span>
                    <div class="right">
                        <form action="<?php echo BASE_URL; ?>completa-tu-registro" method="post" data-parsley-validate="data-parsley-validate">
                            <p>Registrando tu correo electrónico</p>
                            <?php $data = $this->flashMessenger()->getMessagesFromNamespace('data'); ?>
                            <?php $email = isset($data[0]['email']) ? $data[0]['email'] : null; ?>
                            <input type="hidden" id="registro_form" name="registro_form" value="1">
                            <div class="form_control">
                                <input id="email" name="email" type="text" placeholder="ejemplo@micorreo.com" value="<?php echo $email; ?>" data-parsley-type="email" data-parsley-type-message="El correo ingresado no tiene formato válido." data-parsley-required="true" data-parsley-required-message="Este campo es requerido y no puede estar vacío" class="center"/>
                                <?php if (!empty($messageExistsEmail)) : ?>
                                    <ul class="parsley-errors-list filled">
                                        <li class="parsley-required"><?php echo $messageExistsEmail; ?></li>
                                    </ul>
                                <?php endif; ?>
                                <?php $flashMessage = $this->flashMessenger()->getMessages(); ?>
                                <?php if (count($flashMessage) > 0) : ?>
                                    <?php foreach ($flashMessage as $msg) : ?>
                                        <ul class="parsley-errors-list filled">
                                        <?php foreach ($msg as $type => $message) : ?>
                                            <li class="parsley-required"><?php echo $message; ?></li>
                                        <?php endforeach; ?>
                                        </ul>
                                    <?php endforeach; ?>                                
                                <?php endif; ?>
                            </div>
                            
                            <button class="btn btn_orange">Registrarme</button>
                        </form>
                    </div>
                </div>
                <hr/>
                <div class="login_link"><a href="<?php echo BASE_URL; ?>login">Ya tengo una cuenta en Coner Park<span></span></a></div>
            </div>
            <div class="how_to_signin">
                <div class="col_4">
                    <div class="image"><img src="<?php echo URL_RESOURCES . 'front/images/step_1.png?' . VERSION_STATICO ?>" alt=""></div>
                    <p>Regístrate en esta página.</p>
                </div>
                <div class="col_4">
                    <div class="image"><img src="<?php echo URL_RESOURCES . 'front/images/step_2.png?' . VERSION_STATICO ?>" alt=""></div>
                    <p>Confirma tu cuenta de correo.</p>
                </div>
                <div class="col_4">
                    <div class="image"><img src="<?php echo URL_RESOURCES . 'front/images/step_3.png?' . VERSION_STATICO ?>" alt=""></div>
                    <p>Asocia tu tarjeta a la cuenta que acabas de crear.</p>
                </div>
                <div class="col_4">
                    <div class="image"><img src="<?php echo URL_RESOURCES . 'front/images/step_4.png?' . VERSION_STATICO ?>" alt=""></div>
                    <p>¡Disfruta de todos los descuentos que tenemos para ti!.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<script type="text/javascript">
    $(document).ready(function(){
        $('.btn_fb').click(function(){location.href = $(this).data('href');});
        $('.btn_tw').click(function(){location.href = $(this).data('href');});
    });
</script>