
<p class="login-box-msg">Registrate</p>
<a href="<?php echo BASE_URL; ?>login/validate-social/facebook">Facebook</a>
<a href="<?php echo BASE_URL; ?>login/validate-social/twitter">Twitter</a>
<br>
<form action="<?php echo BASE_URL; ?>completa-tu-registro" method="post">
    <input type="hidden" id="registro_form" name="registro_form" value="1">
    <input type="text" id="email" name="email" placeholder="Correo electrónico">
    <input type="submit" value="Registrarme">
</form>