<?php $this->form->prepare(); ?>
<?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-horizontal')); ?>
Password
<?php echo $this->formElement($this->form->get('password')->setAttribute('class', 'form-control')) ?>
<span class="error"><?php echo $this->formElementerrors($form->get('password')); ?></span>
<br>
Repetir password
<?php echo $this->formElement($this->form->get('password_repeat')->setAttribute('class', 'form-control')) ?>
<span class="error"><?php echo $this->formElementerrors($form->get('password_repeat')); ?></span>

<?php echo $this->formElement($this->form->get('codigo')); ?>
<?php echo $this->formRow($form->get('token_csrf')); ?>
<?php echo $this->formInput($form->get('aceptar')); ?>

<?php echo $this->form()->closeTag(); ?>