<?php $this->form->prepare(); ?>
<?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-horizontal')); ?>

<?php echo $this->formElement($this->form->get('email')->setAttribute('class', 'form-control')) ?>
<span class="error"><?php echo $this->formElementerrors($form->get('email')); ?></span>

<?php echo $this->formRow($form->get('token_csrf')); ?>
<?php echo $this->formInput($form->get('aceptar')); ?>

<?php echo $this->form()->closeTag(); ?>