<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?php echo $user->urlImg . '/' . $user->image; ?>" onerror="this.src='<?php echo $user->urlImg . '/user-web-default.png'; ?>';" class="img-circle" alt="<?php echo $user->username; ?>">
            </div>
            <div class="pull-left info">
                <p><?php echo $user->username; ?></p>
                <a href="<?php echo $user->urlProfile; ?>"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <ul class="sidebar-menu">
        <?php foreach ($menus as $parent) :?>
            <?php $classActive = $parent['active'] ? 'active' : ''; ?>
            <li class="<?php echo $classActive; ?> treeview">
                <a href="<?php echo (empty($parent['url']) ? 'javascript:;' : BASE_URL . $parent['url']); ?>">
                    <i class="fa <?php echo $parent['icono']; ?>"></i> 
                    <span><?php echo $parent['nombre']; ?></span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <?php $children1 = isset($parent['hijos']) ? $parent['hijos'] : array(); ?>
                <?php if (!empty($children1)) : ?>
                    <ul class="treeview-menu">
                        <?php foreach ($children1 as $child1) : ?>
                        <?php $classActive = $child1['active'] ? 'active' : ''; ?>
                            <li class="<?php echo $classActive; ?>"><a href="<?php echo BASE_URL . $child1['url']; ?>"><i class="fa <?php echo  $child1['icono']; ?>"></i><?php echo  $child1['nombre']; ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
    </section>
</aside>