<?php $this->form->prepare(); ?>
<?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-inline isearch')); ?>
    <div class="box-body">
        <div class="form-group">
            <label class="control-label" for="rol_id">Rol</label>
            <?php echo $this->formElement($this->form->get('rol_id')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="recurso_id">Recurso</label>
            <?php echo $this->formElement($this->form->get('recurso_id')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Buscar</button>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>