<?php $this->form->prepare(); ?>
<div class="box">
    <div class="box-header with-border">
        <label>Permiso</label>
    </div>
    <?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-horizontal')); ?>
    <div class="box-body">        
        <div class="form-group">
            <label class="col-sm-2 control-label" for="rol_id">Rol <span>*</span></label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('rol_id')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('rol_id')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="recurso_id">Recurso <span>*</span></label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('recurso_id')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('recurso_id')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="listar">Listar</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('listar')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('listar')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="crear">Crear</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('crear')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('crear')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="modificar">Modificar</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('modificar')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('modificar')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="eliminar">Eliminar</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('eliminar')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('eliminar')); ?></span>
            </div>
        </div>
        <div class="box-footer">
            <a class="btn btn-default" href="<?php echo BASE_URL; ?>admin/permiso/index">Regresar</a>
            <button class="btn btn-success" type="submit">Aceptar</button>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>