<?php $this->layout()->title = array('Permisos', 'Listado') ?>
<?php
$this->layout()->breadcrumb = array(
    array('url' => null, 'name' => 'Permisos'),
    array('url' => null, 'name' => 'Listado'),
);
?>

<div class="box">
    <div class="box-header with-border">
        <?php echo $this->partial('admin/permiso/_buscar.phtml', array('form' => $form)); ?>
    </div>
    <div class="box-body">
        <?php echo $this->showMessenger($this->flashMessenger()->getMessages()); ?>
        <a href="<?php echo BASE_URL; ?>admin/permiso/crear" class="btn btn-success">Registrar</a>
        <hr class="separator">
        <table id="gridMain" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Rol</th>
                    <th>Recurso</th>
                    <th>Permisos</th>
                    <th style="max-width: 60px"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($gridList as $row) : ?>
                    <tr>
                        <td><?php echo $row['rol_nombre'] ?></td>
                        <td><?php echo $row['recurso_nombre'] ?></td>
                        <td>
                            <?php 
                            $acl = array();
                            (strpos($row['acl'], 'R') === false) ? '' : $acl[] = 'Listar';
                            (strpos($row['acl'], 'C') === false) ? '' : $acl[] = 'Crear';
                            (strpos($row['acl'], 'U') === false) ? '' : $acl[] = 'Modificar';
                            (strpos($row['acl'], 'D') === false) ? '' : $acl[] = 'Eliminar';
                            ?>
                            <?php echo implode(' - ', $acl); ?>
                        </td>
                        <td>
                            <a href="<?php echo BASE_URL ?>admin/permiso/editar/<?php echo $row['id']; ?>" class="btn btn-primary" title="Editar"><i class="fa fa-edit"></i></a>
                            <a href="<?php echo BASE_URL ?>admin/permiso/eliminar/<?php echo $row['id']; ?>" class="btn btn-danger delete-remote" title="Eliminar"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#gridMain').DataTable({
            "pageLength": 25,
            "paging": true,
            "lengthChange": true,
            "searching": false,
            "ordering": false,
            "language": {
                "lengthMenu": "Mostrar _MENU_ registros",
                "info": "Registros de _START_ al _END_, de un total de <?php echo $countList; ?>"
            },
            "autoWidth": true
        });
        common.deleteRemote();
    });
</script>