<?php $this->form->prepare(); ?>
<?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-inline isearch')); ?>
    <div class="box-body">
        <div class="form-group">
            <label class="control-label" for="comprobante_tipo">Comprobante_tipo</label>
            <?php echo $this->formElement($this->form->get('comprobante_tipo')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="comprobante_numero">Comprobante_numero</label>
            <?php echo $this->formElement($this->form->get('comprobante_numero')->setAttribute('class', 'form-control')) ?>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>