<?php $this->layout()->title = array('Orden', 'Listado') ?>
<?php
$this->layout()->breadcrumb = array(
    array('url' => null, 'name' => 'Orden'),
    array('url' => null, 'name' => 'Listado'),
);
?>

<div class="box">
    <div class="box-header with-border">
        <?php echo $this->partial('orden/orden/_buscar.phtml', array('form' => $form)); ?>
    </div>
    <div class="box-body">
        <?php echo $this->showMessenger($this->flashMessenger()->getMessages()); ?>
        <a href="javascript:exportarExcel()" class="btn btn-success">Excel</a>
        <hr class="separator">
        <table id="gridMain" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Id</th>
                <th>Cod. Pago</th>
                <th>Correo</th>
                <th>Metodo</th>
                <th>Monto</th>
                <th>F. Confirmacion</th>
                <th>Estado</th>
                <th>Comprobante</th>
                <th>Nro. Comprobante</th>
                <th>R. Social</th>
                <th>Nombres</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($gridList as $row) : ?>
                <tr>
                    <td><?php echo $row['id'] ?></td>
                    <td><?php echo $row['email'] ?></td>
                    <td><?php echo $row['email'] ?></td>
                    <td><?php echo \Orden\Model\Service\OrdenService::getNombreTipoPago($row['pago_tarjeta']); ?></td>
                    <td><?php echo $row['monto'] ?></td>
                    <td><?php echo $row['fecha_creacion'] ?></td>
                    <td><?php echo \Orden\Model\Service\OrdenService::getNombreEstadoPago($row['pago_estado']); ?></td>
                    <td><?php echo \Orden\Model\Service\OrdenService::getNombreTipoComprobante($row['comprobante_tipo']); ?></td>
                    <td><?php echo $row['comprobante_numero'] ?></td>
                    <td><?php echo $row['fac_razon_social'] ?></td>
                    <td><?php echo $row['nombres']; ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<link  href="http://dev.recargas.coneypark.pe/s/front/datepicker/css/datepicker.css" rel="stylesheet"></link>
<link  href="http://dev.recargas.coneypark.pe/s/front/datepicker/css/bootstrap_.css" rel="stylesheet"></link>
<script src="/s/front/datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#gridMain').DataTable({
            "pageLength": 25,
            "paging": true,
            "lengthChange": true,
            "searching": false,
            "ordering": false,
            "info": true,
            "autoWidth": true,
            "order": [[ 2, "desc" ]]
        });
        common.deleteRemote();

        $("#txtFechaIni").datepicker({
            format: 'yyyy-mm-dd'
        });

        $("#txtFechaFin").datepicker({
            format: 'yyyy-mm-dd'
        });

        $("#cmbTipoComp").on('change', function() {
            $("#formBuscar").submit();
        });

        $("#cmbEstado").on('change', function() {
            $("#formBuscar").submit();
        });

        $("#cmbMetodoPago").on('change', function() {
            $("#formBuscar").submit();
        });

    });

    function exportarExcel(){
        $("#formBuscar").attr("action","<?php echo BASE_URL; ?>admin/orden/orden/exportarExcel");
        $("#formBuscar").submit();
        $("#formBuscar").attr("action","<?php echo BASE_URL; ?>admin/orden/orden");
    }

</script>