<div class="benefits_offers">
    <p class="yellow_text small_text">Promociones</p>
    <div class="offers_box_two">        
        <?php if (!empty($rows['destacado'])) : ?>
            <?php foreach ($rows['destacado'] as $row) : ?>
                <div class="left">
                    <div class="image"><img src="<?php echo $urlImg . '/' . $row['imagen']; ?>" alt="<?php echo $row['titulo1']; ?>"/></div>
                </div>
                <div class="right">
                    <p class="breadcrumb"><?php echo $row['titulo1']; ?> <a href="#modal_watch_legal" name="modal" class="watch_legal">. Ver legal</a></p>
                    <p><?php echo $row['titulo2']; ?></p>
                    <button class="btn btn_orange">Comprar</button>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
    <div class="offers_box_three">
        <?php foreach ($rows['normal'] as $key => $row) : ?>
            <?php $float = (($key+1)%3 == 0) ? 'right' : 'left'; ?>
            <div class="col_3 <?php echo $float; ?>">
                <div class="box_white">
                    <div class="image"><img src="<?php echo $urlImg . '/' . $row['imagen']; ?>" alt="<?php echo $row['titulo1']; ?>"/></div>
                    <p class="breadcrumb"><?php echo $row['titulo1']; ?> <a href="#modal_watch_legal" name="modal" class="watch_legal">. Ver legal</a></p>
                    <p><?php echo $row['titulo2']; ?></p>
                </div>
                <button class="btn btn_orange">Comprar</button>
            </div>
        <?php endforeach; ?>
    </div>
</div>