<div class="offers_box_three carrito_offers">
    <?php foreach ($rows['normal'] as $key => $row) : ?>
        <?php $float = (($key+1)%3 == 0) ? 'right' : 'left'; ?>
        <div class="col_3 <?php echo $float; ?>">
        	<div class="box_white">
        		<div class="image">
        			<a href=""><img src="<?php echo $urlImg . '/' . $row['imagen']; ?>" alt="<?php echo $row['titulo1']; ?>"/></a>
        		</div>
	            <p class="breadcrumb" style="text-align:center;">Promocion 1
                </p>
	            <p><?php echo $row['titulo2']; ?></p>
	            
	        </div>
	        <button class="btn btn_orange btnComprar">Comprar</button>
        </div>
    <?php endforeach; ?>
</div>