<div class="offers_box">
    <?php foreach ($rows as $key => $row) : ?>
        <?php $float = (($key+1)%3 == 0) ? 'right' : 'left'; ?>
        <div class="col_3 <?php echo $float; ?>">
            <div class="image_radius">
	            <a href=""><img src="<?php echo $urlImg . '/' . $row['imagen']; ?>" alt="<?php echo $row['titulo1']; ?>"/></a>
            </div>
            <p><?php echo $row['titulo2']; ?></p>
        </div>
    <?php endforeach; ?>
</div>