<p class="yellow_text small_text">Promociones</p>
<div class="offers">
    <div class="col_3">
        <div class="box_white">
            <div class="image"><img src="../images/benefit_1.png" alt=""/></div>
            <p class="breadcrumb">Promoción 1 <a href="#modal_watch_legal" name="modal" class="watch_legal">Ver legal</a><span></span></p>
            <p>Recarga <strong>S/.100 </strong>y obten <strong>S/.50 </strong>soles adicionales <strong>+ S/.30 </strong>en Coney Bonos</p>
        </div>
        <div class="cant_box"><span class="less">-</span>
            <input type="text" value="0" placeholder="0" class="cant"/><span class="more">+</span>
        </div>
    </div>
    <div class="col_3"></div>
    <div class="col_3"></div>
</div>