<?php $this->form->prepare(); ?>
<?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-inline isearch')); ?>
    <div class="box-body">
        <div class="form-group">
            <label class="control-label" for="usuario_id">Usuario_id</label>
            <?php echo $this->formElement($this->form->get('usuario_id')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="pago_referencia">Pago_referencia</label>
            <?php echo $this->formElement($this->form->get('pago_referencia')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="pago_estado">Pago_estado</label>
            <?php echo $this->formElement($this->form->get('pago_estado')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="pago_tarjeta">Pago_tarjeta</label>
            <?php echo $this->formElement($this->form->get('pago_tarjeta')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="monto_total">Monto_total</label>
            <?php echo $this->formElement($this->form->get('monto_total')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="estado">Estado</label>
            <?php echo $this->formElement($this->form->get('estado')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="fecha_creacion">Fecha_creacion</label>
            <?php echo $this->formElement($this->form->get('fecha_creacion')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="fecha_edicion">Fecha_edicion</label>
            <?php echo $this->formElement($this->form->get('fecha_edicion')->setAttribute('class', 'form-control')) ?>
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Buscar</button>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>