<?php $this->layout()->title = array('Operaciones', 'Listado') ?>
<?php
$this->layout()->breadcrumb = array(
    array('url' => null, 'name' => 'Operaciones'),
    array('url' => null, 'name' => 'Listado'),
);
?>

<div class="box">
    <div class="box-header with-border">
        <?php echo $this->partial('orden/carrito/_buscar.phtml', array('form' => $form)); ?>
    </div>
    <div class="box-body">
        <?php echo $this->showMessenger($this->flashMessenger()->getMessages()); ?>
        <a href="<?php echo BASE_URL; ?>orden/carrito/crear" class="btn btn-success">Exportar</a>
        <hr class="separator">
        <table id="gridMain" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Usuario_id</th>
                    <th>Pago_referencia</th>
                    <th>Pago_estado</th>
                    <th>Pago_tarjeta</th>
                    <th>Monto_total</th>
                    <th>Estado</th>
                    <th>Fecha_creacion</th>
                    <th>Fecha_edicion</th>
                    <th style="max-width: 60px"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($gridList as $row) : ?>
                    <tr>
                        <td><?php echo $row['usuario_id'] ?></td>
                        <td><?php echo $row['pago_referencia'] ?></td>
                        <td><?php echo $row['pago_estado'] ?></td>
                        <td><?php echo $row['pago_tarjeta'] ?></td>
                        <td><?php echo $row['monto_total'] ?></td>
                        <td><?php echo $row['estado'] ?></td>
                        <td><?php echo $row['fecha_creacion'] ?></td>
                        <td><?php echo $row['fecha_edicion'] ?></td>
                        <td>
                            <a href="<?php echo BASE_URL ?>orden/carrito/editar/<?php echo $row['id']; ?>" class="btn btn-primary" title="Editar"><i class="fa fa-edit"></i></a>
                            <a href="<?php echo BASE_URL ?>orden/carrito/eliminar/<?php echo $row['id']; ?>" class="btn btn-danger delete-remote" title="Eliminar"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<link  href="http://dev.recargas.coneypark.pe/s/front/datepicker/css/datepicker.css" rel="stylesheet"></link>
<link  href="http://dev.recargas.coneypark.pe/s/front/datepicker/css/bootstrap_.css" rel="stylesheet"></link>
<script src="/s/front/datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#gridMain').DataTable({
            "pageLength": 25,
            "paging": true,
            "lengthChange": true,
            "searching": false,
            "ordering": false,
            "info": true,
            "autoWidth": true
        });
        common.deleteRemote();

        $("#txtFechaIni").datepicker({
            format: 'yyyy-mm-dd'
        });

        $("#txtFechaFin").datepicker({
            format: 'yyyy-mm-dd'
        });
    });
</script>