<section class="app_content">
    <div class="box_center">
        <div class="app_box">
            <div class="menu left_active">
                <ul>
                    <li class="first active"><a href="<?php echo BASE_URL; ?>beneficios">Beneficios</a></li>
                    <li><a href="<?php echo BASE_URL; ?>mis-tarjetas">Mis tarjetas</a></li>
                    <li class="last"><a href="<?php echo BASE_URL; ?>recargas">Recargas</a></li>
                </ul>
            </div>
            <div class="purple_box">
                <p class="yellow_text small_text">Beneficios para ti</p>
                <p class="small_text">Por ser <strong>miembro del Coney Club </strong>cuentas con las siguientes grandes beneficios</p>
                <div class="options">
                    <div class="col_3 left">
                        <div class="circle">
                            <img src="" alt="">
                        </div>
                        <p class="p_16">Hasta <span> <strong>20% de descuento en todos los juegos. </strong></span>Según el tipo de local</p>
                    </div>
                    <div class="col_3 left">
                        <div class="circle">
                            <img src="" alt="">
                        </div>
                        <p class="p_16"><span><strong>20 Coney Bonos gratis </strong></span>el día de tu cumpleaños (Presentando su DNI)</p>
                    </div>
                    <div class="col_3 right">
                        <div class="circle">
                            <img src="" alt="">
                        </div>
                        <p class="p_16"><span><strong>Descuentos exclusivos </strong></span>por recargas en fechas especiales (Día de los enamorados, día de la madre y padre, halloween, etc.)</p>
                    </div>
                </div>
                <div class="bar_info">
                    <div class="left">
                        <p class="p_16">Asocia tus tarjetas, haciendo clic en el siguiente botón: </p>
                    </div>
                    <div class="right">
                        <button id="mis_tarjetas" class="btn btn_orange"> <span class="text">Asociar tarjetas</span><span class="icon"></span></button>
                    </div>
                </div>
                <?php echo $this->sectionGrillaPromociones(GRID_PROMOCIONES_BENEFICIOS, 1, 'beneficios');  ?>
                <hr/>
                <!--div class="info_box"><span class="icon"></span><span class="text">También puedes acercarte a cualquiera de nuestras sedes, indicando tu cuenta de correo electrónico junto con la tarjeta que desees recargar.</span></div-->
            </div>
        </div>
        
    </div>
    <div id="modal_watch_legal" class="modal_box">
      <div class="modal_content">
        <h3>Importante:</h3>
        <hr/>
        <div class="text_box">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt leo erat. Maecenas dapibus, diam quis dapibus elementum, risus diam congue risus, vitae tristique magna orci et sem. Aliquam congue ut tellus eu ultricies. Vestibulum tristique sapien sit amet accumsan feugiat. Integer congue suscipit dictum. Ut a nisl tempus, ornare erat at, ultrices lectus. Suspendisse pulvinar eros vel finibus ultricies. Maecenas lacinia, tellus ac egestas tincidunt, turpis ipsum pulvinar arcu, et blandit purus lectus vitae odio. Phasellus lobortis, orci non efficitur consectetur, mauris urna ornare nisl, non sodales lectus sapien ac diam. Morbi ligula lorem, tristique in cursus et, vulputate quis lorem. Suspendisse ut erat turpis. </p>
          <p>Sed sed tellus pulvinar, lobortis est sit amet, mollis lectus. Suspendisse semper vestibulum erat at lacinia. Mauris eget quam sit amet magna rutrum maximus in sed ipsum. Etiam libero justo, dictum non malesuada ut, ullamcorper at leo. Vestibulum accumsan condimentum lectus, et faucibus justo sodales non. Aliquam dictum ipsum sit amet nisl elementum commodo ut ut ligula. Aliquam sagittis fermentum gravida. Vestibulum eu neque eget neque placerat ullamcorper at sit amet mauris. Morbi tellus odio, lacinia a libero sed, congue cursus urna. </p>
          <p>Suspendisse potenti. Quisque ipsum ante, luctus quis leo sit amet, mattis convallis enim. Donec feugiat vehicula felis. In lacinia quis est eget tempus. Pellentesque vulputate augue vel nibh sagittis sollicitudin. Etiam eu laoreet tellus. Sed id fermentum lorem. Fusce feugiat, libero nec finibus egestas, tellus risus dignissim dui, ultricies condimentum lectus erat et leo. Integer semper erat sit amet ex tempor, sed eleifend libero venenatis. Proin a arcu quis arcu dapibus tristique. Fusce vehicula diam vitae diam faucibus rutrum quis et leo. Nullam ex metus, mollis eget dignissim quis, bibendum et mauris. Integer bibendum, lacus sit amet tincidunt aliquam, sapien arcu tempor nisi, eget egestas massa felis ut purus. Nulla a purus a nisl tincidunt scelerisque. Proin tempor arcu et tortor lacinia, ac pellentesque eros consectetur. Aenean eget eros in lectus auctor finibus ac nec ex.</p>
        </div>
      </div>
    </div>
    <div id="mask"></div>
</section>
<script type="text/javascript">
    $(document).ready(function(){
        $('#mis_tarjetas').click(function(){location.href = '<?php echo BASE_URL ?>mis-tarjetas';});
    });
</script>