<section class="app_content">
    <div class="box_center">
        <div class="app_box">
            <div class="menu">
                <ul>
                    <li class="first active">Beneficios</li>
                    <li>Mis tarjetas</li>
                    <li class="last">Recargas</li>
                </ul>
            </div>
            <div class="purple_box">
                <p class="yellow_text small_text">Beneficios para ti</p>
                <p class="small_text">Por ser <strong>miembro del Coney Club </strong>cuentas con las siguientes grandes beneficios</p>
                <div class="options">
                    <div class="col_3 left">
                        <div class="circle"></div>
                        <p class="p_16">Hasta <span> <strong>20% de descuento en todos los juegos. </strong></span>Según el tipo de local</p>
                    </div>
                    <div class="col_3 left">
                        <div class="circle"></div>
                        <p class="p_16"><span><strong>20 Coney Bonos gratis </strong></span>el día de tu cumpleaños (Presentando su DNI)</p>
                    </div>
                    <div class="col_3 right">
                        <div class="circle"></div>
                        <p class="p_16"><span><strong>Descuentos exclusivos </strong></span>por recargas en fechas especiales (Día de los enamorados, día de la madre y padre, halloween, etc.)</p>
                    </div>
                </div>
                <div class="bar_info">
                    <div class="left">
                        <p class="p_16">Asocia tus tarjetas, haciendo clic en el siguiente botón: </p>
                    </div>
                    <div class="right">
                        <button class="btn btn_orange"> <span class="text">Asociar tarjetas</span><span class="icon"></span></button>
                    </div>
                </div>
                <?php echo $this->sectionGrillaPromociones(GRID_BENEFICIOS_PROMOCIONES, 1, 'beneficios');  ?>
                <hr/>
                <div class="info_box"><span class="icon"></span><span class="text">También puedes acercarte a cualquiera de nuestras sedes, indicando tu cuenta de correo electrónico junto con la tarjeta que desees recargar.</span></div>
            </div>
        </div>
    </div>
</section>
