<section>
    <div class="box_center">
        <div class="welcome_box">
            <?php echo $this->sectionContenido(Cms\Model\Service\ContenidoService::SECCION_LOGIN_INICIO_SESION); ?>
<!--            <h2>¡Ahora <span>recárgate de diversión </span>con un click!</h2>
            <p class="subtitle">Te invitamos a ser parte de Coney Club y a realizar todas tus recargas de una manera más rápida, <strong>sin necesidad de hacer colas</strong>, además, tendrás <strong>promociones exclusivas </strong>que no te puedes perder.</p>-->
            <div class="yellow_box">Inicia sesión</div>
            <div class="purple_box">
                <div class="success_message" style="display:none;"><span class="icon"></span><span class="text">Es necesario iniciar sesión para acceder a todas las promociones.</span></div>
                <?php $flashMessage = $this->flashMessenger()->getMessages(); ?>
                <?php if (count($flashMessage) > 0) : ?>
                    <?php foreach ($flashMessage as $msg) : ?>
                        <?php foreach ($msg as $type => $message) : ?>
                            <div class="error_message"><span class="icon"></span><span class="text"><?php echo $message; ?></span></div>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                <div class="content">
                    <div class="left">
                        <p>Usando tus redes sociales</p>
                        <button class="btn btn_fb" data-href="<?php echo BASE_URL; ?>login/validate-social/facebook"><span class="icon"></span><span class="text">Facebook</span></button>
                        <button class="btn btn_tw" data-href="<?php echo BASE_URL; ?>login/validate-social/twitter"><span class="icon"></span><span class="text">Twitter</span></button>
                    </div>
                    <span class="or_icon"></span>
                    <div class="right">
                        <p>Con tu correo electrónico</p>
                        <?php $form = $this->form->setAttribute('data-parsley-validate', 'data-parsley-validate')->prepare(); ?>
                        <?php echo $this->form()->openTag($form); ?>
                        <div class="form_control">
                            <?php
                            echo $this->formInput($form->get('email')->setAttributes(array(
                                        'placeholder' => 'ejemplo@micorreo.com',
                                        'data-parsley-required' => 'data-parsley-required',
                                        'data-parsley-required-message' => 'El campo es requerido y no puede estar vacío.',
                                        'data-parsley-type' => 'email',
                                        'data-parsley-type-message' => 'El correo ingresado no tiene formato válido.',
                                        'class' => 'email center',
                            )));
                            ?>
                            <ul class="parsley-errors-list filled">
                                <li class="parsley-required"><?php echo $this->formElementerrors($form->get('email')); ?></li>
                            </ul>
                        </div>
                        <div class="form_control">
                            <?php
                            echo $this->formInput($form->get('password')->setAttributes(array(
                                        'placeholder' => 'contraseña',
                                        'data-parsley-required' => 'data-parsley-required',
                                        'data-parsley-required-message' => 'El campo es requerido y no puede estar vacío.',
                                        'class' => 'password center',
                            )));
                            ?>
                            <ul class="parsley-errors-list filled">
                                <li class="parsley-required"><?php echo $this->formElementerrors($form->get('password')); ?></li>
                            </ul>
                        </div>
                        <?php echo $this->formRow($form->get('token_csrf')); ?>
                        <button type="submit" class="btn btn_orange btn_login">Iniciar Sesión</button>
                        <?php echo $this->form()->closeTag(); ?>
                        <div class="login_link"><a href="#modal_recovery_password" name="modal">Olvidé mi contraseña</a></div>
                    </div>
                </div>
                <hr/>
                <div class="login_link"><a href="<?php echo BASE_URL; ?>registrate">Aún no tengo cuenta como socio de Coney Club<span></span></a></div>
            </div>
            <?php echo $this->sectionGrillaPromociones(GRID_PROMOCIONES_LOGIN, 'login');  ?>
        </div>
        
    </div>

    <div id="modal_recovery_password" class="modal_box">
        <div class="modal_content modal_recovery_content"><span class="icon_logo"></span>
            
            <h3>Recuperar contraseña</h3>
            <p>Ingresa la dirección de correo electrónico que usaste para registrarte.</p>
            <input id="email_recuperar" name="email_recuperar" class="center" type="text" placeholder="Correo electrónico" data-parsley-required data-parsley-required-message="El campo es requerido y no puede estar vacío." data-parsley-type="email" data-parsley-type-message="Ingrese un correo válido."/>
            <ul class="parsley-errors-list filled">
                <li id="error_recuperar_password" class="parsley-required"></li>
            </ul>
            <button id="btn_recovery" class="btn btn_orange">Recuperar contraseña</button>
           
        </div>
    </div>
    <div id="modal_recovery_response" class="modal_box">
        <div class="modal_content modal_recovery_content"><span class="icon_logo"></span>
            <h3>Recuperar contraseña</h3>
            <p>Felicidades, ya estás a punto de ser parte de Coney Club. 
                Te hemos enviado un correo con las instrucciones para recuperar tu contraseña.</p>
            <button class="close btn btn_orange">Aceptar</button>
        </div>
    </div>
    <div id="modal_new_password" class="modal_box" data-open="<?php echo $openPopapChangePassword; ?>">
        <div class="modal_content modal_recovery_content"><span class="icon_logo"></span>
            <h3>Nueva contraseña</h3>
            <p>Ingresa una nueva contraseña</p>
            <div class="form_control">
                <input id="password_new" name="password_new" type="password"  class="center" placeholder="Ingresa tu nueva contraseña"/>
            </div>
            <div class="form_control">
                <input id="password_repeat" name="password_repeat" class="center" type="password" placeholder="Repite tu nueva contraseña"/>
            </div>
            
            <input id="codigo_recuperacion" name="codigo_recuperacion" type="hidden" value="<?php echo isset($codigoRecuperacion) ? $codigoRecuperacion : ''; ?>"/>
            <ul class="parsley-errors-list filled">
                <li id="error_new_password" class="parsley-required"></li>
            </ul>
            <button id="btn_change_password" class="btn btn_orange">Cambiar contraseña</button>
        </div>
    </div>
    <div id="modal_new_password_response" class="modal_box">
        <div class="modal_content modal_recovery_content"><span class="icon_logo"></span>
            <h3>Nueva contraseña</h3>
            <p>Felicidades, tu contraseña se actualizó correctamente</p>
            <button class="close btn btn_orange">Aceptar</button>
        </div>
    </div>
    <div id="mask"></div>

</section>
<script type="text/javascript">
    $(document).ready(function(){
        $('.btn_fb').click(function(){location.href = $(this).data('href');});
        $('.btn_tw').click(function(){location.href = $(this).data('href');});
    });
</script>