<?php $this->form->prepare(); ?>
<?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-inline isearch')); ?>
    <div class="box-body">
        <div>
            <div class="form-group">
                <label class="control-label" for="tipo"><strong>Buscar por</strong> </label>
                <?php echo $this->formElement($this->form->get('cmbFiltro')->setAttribute('class', 'form-control')) ?>
            </div>
            <div class="form-group">
                <?php echo $this->formElement($this->form->get('txtBuscar')->setAttribute('class', 'form-control')) ?>
            </div>
            <div class="form-group">
                <button id="btnBuscar" class="btn btn-primary" type="submit">Buscar</button>
            </div>
        </div>
        <div class="filter-title">
            <div class="form-group">
                <label class="control-label">Filtrar por:</label>
            </div>
        </div>
        <div class="filter-one">
            <div class="form-group">
                <label class="control-label" for="tipo">Estado</label>
                <?php echo $this->formElement($this->form->get('cmbEstado')->setAttribute('class', 'form-control')) ?>
            </div>
            <div class="form-group">
                <label class="control-label" for="tipo">Estado pago </label>
                <?php echo $this->formElement($this->form->get('cmbPagoEstado')->setAttribute('class', 'form-control')) ?>
            </div>
            <div class="form-group">
                <label class="control-label" for="tipo">Tipo comprobate </label>
                <?php echo $this->formElement($this->form->get('cmbTipoComp')->setAttribute('class', 'form-control')) ?>
            </div>
            <div class="form-group">
                <label class="control-label" for="tipo">Metodo</label>
                <?php echo $this->formElement($this->form->get('cmbMetodoPago')->setAttribute('class', 'form-control')) ?>
            </div>

        </div>
        <div class="filter-two">
            <div class="form-group">
                <label class="control-label" for="tipo">Desde</label>
                <?php echo $this->formElement($this->form->get('txtFechaIni')->setAttribute('class', 'form-control')) ?>
            </div>
            <div class="form-group">
                <label class="control-label" for="tipo">Hasta</label>
                <!--<div class="input-append date" id="FechaFin">
                    <input class="span2" size="16" type="text" readonly="">
                    <span class="add-on"><i class="icon-calendar"></i></span>
                </div>-->
                <?php echo $this->formElement($this->form->get('txtFechaFin')->setAttribute('class', 'form-control')) ?>
            </div>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>
