<?php $this->layout()->title = array('Transacciones', 'Listado') ?>
<?php
$this->layout()->breadcrumb = array(
    array('url' => null, 'name' => 'Orden'),
    array('url' => null, 'name' => 'Listado'),
);
?>

<div class="box">
    <div class="box-header with-border">
        <?php echo $this->partial('admin/orden/_buscar.phtml', array('form' => $form)); ?>
    </div>
    <div class="box-body">
        <?php echo $this->showMessenger($this->flashMessenger()->getMessages()); ?>
        <a href="javascript:exportarExcel()" class="btn btn-success">Exportar</a>
        <hr class="separator">
        <table id="gridMain" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Id</th>
                <th style="white-space:nowrap;">Código Transaccion</th>
                <th style="white-space:nowrap;">Pago Referencia</th>
                <th>Correo</th>
                <th style="white-space:nowrap;">Método Pago</th>
                <th>Monto</th>
                <th style="white-space:nowrap;">F. Confirmación</th>
                <th>Estado</th>
                <th style="white-space:nowrap;">Pago Estado</th>
                <th>Comprobante</th>
                <th style="white-space:nowrap;">Tipo Documento</th>
                <th style="white-space:nowrap;">Nro. Documento</th>
                <th style="white-space:nowrap;">Razón Social</th>
                <th>Nombres</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($gridList as $row) : ?>
                <tr>
                    <td><?php echo $row['id']; ?></td>
                    <td><?php echo $row['codigo']; ?></td>
                    <td><?php echo $row['pago_referencia']; ?></td>
                    <td><?php echo $row['email']; ?></td>
                    <td><?php echo $row['pago_metodo']; ?></td>
                    <td><?php echo $row['monto']; ?></td>
                    <td><?php echo $row['pago_fecha_confirmacion']; ?></td>
                    <td><?php echo $row['estado']; ?></td>
                    <td><?php echo $row['pago_estado']; ?></td>
                    <td><?php echo \Admin\Model\Service\OrdenService::getNombreTipoComprobante($row['comprobante_tipo']); ?></td>
                    <td><?php echo \Admin\Model\Service\OrdenService::getNombreTipoDocumento($row['documento_tipo']); ?></td>
                    <td><?php echo $row['documento_numero'] ?></td>
                    <td><?php echo $row['fac_razon_social']; ?></td>
                    <td><?php echo $row['nombres']; ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#gridMain').DataTable({
            "pageLength": 25,
            "paging": true,
            "lengthChange": true,
            "searching": false,
            "ordering": false,
            "info": true,
            "autoWidth": true,
            "order": [[ 2, "desc" ]]
        });
        common.deleteRemote();

        $("#txtFechaIni").datepicker({
            format: 'yyyy-mm-dd'
        }).on('changeDate', function(e){
            $("#formBuscar").submit();
        });

        $("#txtFechaFin").datepicker({
            format: 'yyyy-mm-dd'
        }).on('changeDate', function(e){
            $("#formBuscar").submit();
        });

        $("#cmbTipoComp").on('change', function() {
            $("#formBuscar").submit();
        });

        $("#cmbPagoEstado").on('change', function() {
            $("#formBuscar").submit();
        });

        $("#cmbEstado").on('change', function() {
            $("#formBuscar").submit();
        });

        $("#cmbMetodoPago").on('change', function() {
            $("#formBuscar").submit();
        });

    });

    function exportarExcel(){
        $("#formBuscar").attr("action","<?php echo BASE_URL; ?>admin/orden/exportar-excel");
        $("#formBuscar").submit();
        $("#formBuscar").attr("action","<?php echo BASE_URL; ?>admin/orden");
    }

</script>