<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'Admin',
        'Common',
        'Application',
        'Usuario',
        'Orden',
        'Tarjeta',
        'Paquete',
        'Sistema',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './web',
            './vendor',
            './common',
        ),
        'config_glob_paths' => array(
            'config/autoload/{{,*.}constants,{,*.}global,{,*.}local}.php',
        ),
    ),
);
