<?php $this->form->prepare(); ?>
<div class="box">
    <div class="box-header with-border">
        <label>Paquete</label>
    </div>
    <?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-horizontal')); ?>
    <div class="box-body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="titulo1">Titulo 1 <span>*</span></label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('titulo1')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('titulo1')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="titulo2">Titulo 2</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('titulo2')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('titulo2')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="tipo">Tipo <span>*</span></label>
            <div class="col-sm-3">
                <?php echo $this->formElement($this->form->get('tipo')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('tipo')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="emoney">Orden <span>*</span></label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('orden')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('orden')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="emoney">Dinero <span>*</span></label>
            <div class="col-sm-8">
                <label><?php echo $this->form->get('emoney')->getValue(); ?></label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="bonus">Coney Bonos <span>*</span></label>
            <div class="col-sm-8">
                <label><?php echo $this->form->get('bonus')->getValue(); ?></label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="promotionbonus">Coney Bonos Plus <span>*</span></label>
            <div class="col-sm-8">
                <label><?php echo $this->form->get('promotionbonus')->getValue(); ?></label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="etickets">Tickets <span>*</span></label>
            <div class="col-sm-8">
                <label><?php echo $this->form->get('etickets')->getValue(); ?></label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="gamepoints">Game Points <span>*</span></label>
            <div class="col-sm-8">
                <label><?php echo $this->form->get('gamepoints')->getValue(); ?></label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="fecha_creacion">Fecha</label>
            <div class="col-sm-8">
                <label><?php echo $this->form->get('fecha_creacion')->getValue(); ?></label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="activo">Activo</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('activo')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('activo')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="destacado">Destacado</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('destacado')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('destacado')); ?></span>
            </div>
        </div>
        <div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="imagen">Imagen <span>*</span></label>

                <div class="col-sm-10">
                    <?php echo $this->formElement($this->form->get('imagen')); ?>
                    <span class="error"><?php echo $this->formElementerrors($form->get('imagen')); ?></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="legal">Legal</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('legal')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('legal')->setAttribute('class', 'form-control')); ?></span>
            </div>
        </div>
        <div class="box-footer">
            <a class="btn btn-default" href="<?php echo BASE_URL; ?>admin/paquete/index">Regresar</a>
            <button class="btn btn-success" type="submit">Aceptar</button>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        var tipoRecarga = <?php echo \Admin\Model\Service\PaqueteService::TIPO_RECARGA;?>;

        $('#destacado').removeAttr('disabled');
        if ($("#tipo").val() == tipoRecarga) {
            $('#destacado').attr('disabled', true);
        }

        $("#tipo").on('change', function() {
            $('#destacado').removeAttr('disabled');

            if ($("#tipo").val() == tipoRecarga) {
                $('#destacado').attr('disabled', true);
            }
        });

    });
</script>