<?php $this->form->prepare(); ?>
<div class="box">
    <div class="box-header with-border">
        <label>Orden</label>
    </div>
    <?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-horizontal')); ?>
    <div class="box-body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="usuario_id">Usuario_id</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('usuario_id')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('usuario_id')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="comprobante_tipo">Comprobante_tipo</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('comprobante_tipo')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('comprobante_tipo')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="comprobante_numero">Comprobante_numero</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('comprobante_numero')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('comprobante_numero')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="fac_razon_social">Fac_razon_social</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('fac_razon_social')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('fac_razon_social')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="documento_numero">Fac_ruc</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('documento_numero')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('documento_numero')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="fac_direccion_fiscal">Fac_direccion_fiscal</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('fac_direccion_fiscal')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('fac_direccion_fiscal')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="fac_direccion_entrega_factura">Fac_direccion_entrega_factura</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('fac_direccion_entrega_factura')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('fac_direccion_entrega_factura')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="nombres">Nombres</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('nombres')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('nombres')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="paterno">Paterno</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('paterno')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('paterno')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="materno">Materno</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('materno')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('materno')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="ciudadania">Ciudadania</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('ciudadania')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('ciudadania')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="direccion">Direccion</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('direccion')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('direccion')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="pais_id">Pais_id</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('pais_id')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('pais_id')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="distrito_id">Distrito_id</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('distrito_id')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('distrito_id')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="pago_referencia">Pago_referencia</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('pago_referencia')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('pago_referencia')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="pago_estado">Pago_estado</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('pago_estado')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('pago_estado')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="pago_tarjeta">Pago_tarjeta</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('pago_tarjeta')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('pago_tarjeta')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="monto">Monto</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('monto')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('monto')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="estado">Estado</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('estado')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('estado')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="fecha_creacion">Fecha_creacion</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('fecha_creacion')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('fecha_creacion')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="fecha_edicion">Fecha_edicion</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('fecha_edicion')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('fecha_edicion')); ?></span>
            </div>
        </div>
        <div class="box-footer">
            <a class="btn btn-default" href="<?php echo BASE_URL; ?>admin/orden/index">Regresar</a>
            <button class="btn btn-success" type="submit">Aceptar</button>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>