<section class="app_content recargas">
    <div class="box_center">
        <div class="app_box">
            <div class="menu right_active">
                <ul>
                    <li class="first"><a href="<?php echo BASE_URL; ?>beneficios">Beneficios</a></li>
                    <li><a href="<?php echo BASE_URL; ?>mis-tarjetas">Mis tarjetas</a></li>
                    <li class="last active"><a href="<?php echo BASE_URL; ?>recargas">Recargas</a></li>
                </ul>
            </div>
            <div class="purple_box">
                <p class="yellow_text small_text">Recarga de mis tarjetas</p>
                <div class="steps">
                    <div class="step active">1</div>
                    <div class="step">2</div>
                </div>
                <div class="cart_box"><span class="label">Items en el carrito:</span>
                    <div class="cart"><span class="icon"></span><span class="number">0</span></div>
                </div>
                <div class="recargas_content">
                    <?php echo $this->sectionRecargaPromociones();  ?>
                    <?php echo $this->sectionRecargaRecargas();  ?>
                    <br/><br/>
                </div>
            </div>
        </div>
    </div>
</section>
<?php echo $this->sectionCart($usuarioId, $tarjetaCodigo);  ?>

<script type="text/javascript" >
    var cart = {
        bloquear:0,
        seleccionarTarjeta:function(codigo)
        {
            location.href= baseUrl+'recargas/'+codigo;
        },
        sendCart:function(prefix)
        {
            var result = false;
            if (cart.bloquear == 1) {
                return result;
            }

            cart.bloquear = 1;
            $.ajax({
                type: "POST",
                url: '<?php echo BASE_URL; ?>cart/modificar',
                data:{id:$('#id_'+prefix).val(), cantidad:$('#cantidad_'+prefix).val(), tarjeta:$('#tarjeta').val()},
                dataType: 'json',
                async:false,
                success: function(data){
                    if (data.success) {
                        $('#spanSubtotal').html(' <span class="text">Recargas: </span>'+data.data.cantidad+' <span>/ </span>S/. '+data.data.subtotal);
                        $('#spanTotal').html('S/. '+data.data.total);
                        result = true;
                    }
                    cart.bloquear = 0;
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    cart.bloquear = 0;
                }
            });
            
            return result;
        },
        agregar:function(prefix){
            var cantidad = $('#cantidad_'+prefix).val();
            cantidad = ($.trim(cantidad).length < 1) ? 0 : parseInt(cantidad);
            var newCantidad = cantidad >= 5 ? 5 : (cantidad + 1);
            $('#cantidad_'+prefix).val(newCantidad);
            if (cart.sendCart(prefix)) {
                //ok
            } else {
                $('#cantidad_'+prefix).val(cantidad);
            }
        },
        remover:function(prefix) {
            var cantidad = $('#cantidad_'+prefix).val();
            cantidad = ($.trim(cantidad).length < 1) ? 0 : parseInt(cantidad);
            var newCantidad = cantidad < 1 ? 0 : (cantidad - 1);
            $('#cantidad_'+prefix).val(newCantidad);
            if (cart.sendCart(prefix)) {
                //ok
            } else {
                $('#cantidad_'+prefix).val(cantidad);
            }
        },
        init:function() {
            $('.less').each(function(){
                $(this).click(function(){
                    cart.remover($(this).parent().data('prefix'));
                });
            });
            $('.more').each(function(){
                $(this).click(function(){
                    cart.agregar($(this).parent().data('prefix'));
                });
            });
            $('input.cant').each(function(){
                $(this).change(function(){
                    cart.sendCart($(this).parent().data('prefix'));
                });
            });
            $('#tarjeta').change(function(){
               cart.seleccionarTarjeta($(this).val());
            });
        }
    };
    $(document).ready(function (){
        cart.init();
    });
</script>