<section class="app_content recargas">
    <div class="box_center">
        <div class="app_box">
            <div class="menu right_active">
                <ul>
                    <li class="first"><a href="<?php echo BASE_URL; ?>beneficios">Beneficios</a></li>
                    <li><a href="<?php echo BASE_URL; ?>mis-tarjetas">Mis tarjetas</a></li>
                    <li class="last active"><a href="<?php echo BASE_URL; ?>recargas">Recargas</a></li>
                </ul>
            </div>
            <div class="purple_box">
                <p class="yellow_text small_text">Recarga de mis tarjetas</p>
                <div class="steps">
                    <div class="step active">1</div>
                    <span></span>
                    <div class="step">2</div>
                </div>
                <a href="<?php echo BASE_URL ?>carrito" class="cart_box">
                    <span class="label">Items en el carrito:</span>
                    <div class="cart">
                        <span class="icon"></span>
                        <span class="number" id="spanCantidadTotal"><?php echo empty($cartModel) ? 0 : $cartModel->getQuantityCart(); ?></span>
                    </div>
                </a>
                <div class="recargas_content">
                    <?php $tarjetaProductos = empty($cartModel) ? array() : $cartModel->getProductsGroup(); ?>
                    <?php echo $this->sectionRecargaPromociones($tarjetaProductos);  ?>
                    <?php echo $this->sectionRecargaRecargas($tarjetaProductos);  ?>
                    <br/><br/>
                </div>
            </div>
        </div>

    </div>
    <div id="modal_watch_legal" class="modal_box">
          <div class="modal_content">
            <h3>Importante:</h3>
            <hr/>
            <div class="text_box">
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt leo erat. Maecenas dapibus, diam quis dapibus elementum, risus diam congue risus, vitae tristique magna orci et sem. Aliquam congue ut tellus eu ultricies. Vestibulum tristique sapien sit amet accumsan feugiat. Integer congue suscipit dictum. Ut a nisl tempus, ornare erat at, ultrices lectus. Suspendisse pulvinar eros vel finibus ultricies. Maecenas lacinia, tellus ac egestas tincidunt, turpis ipsum pulvinar arcu, et blandit purus lectus vitae odio. Phasellus lobortis, orci non efficitur consectetur, mauris urna ornare nisl, non sodales lectus sapien ac diam. Morbi ligula lorem, tristique in cursus et, vulputate quis lorem. Suspendisse ut erat turpis. </p>
              <p>Sed sed tellus pulvinar, lobortis est sit amet, mollis lectus. Suspendisse semper vestibulum erat at lacinia. Mauris eget quam sit amet magna rutrum maximus in sed ipsum. Etiam libero justo, dictum non malesuada ut, ullamcorper at leo. Vestibulum accumsan condimentum lectus, et faucibus justo sodales non. Aliquam dictum ipsum sit amet nisl elementum commodo ut ut ligula. Aliquam sagittis fermentum gravida. Vestibulum eu neque eget neque placerat ullamcorper at sit amet mauris. Morbi tellus odio, lacinia a libero sed, congue cursus urna. </p>
              <p>Suspendisse potenti. Quisque ipsum ante, luctus quis leo sit amet, mattis convallis enim. Donec feugiat vehicula felis. In lacinia quis est eget tempus. Pellentesque vulputate augue vel nibh sagittis sollicitudin. Etiam eu laoreet tellus. Sed id fermentum lorem. Fusce feugiat, libero nec finibus egestas, tellus risus dignissim dui, ultricies condimentum lectus erat et leo. Integer semper erat sit amet ex tempor, sed eleifend libero venenatis. Proin a arcu quis arcu dapibus tristique. Fusce vehicula diam vitae diam faucibus rutrum quis et leo. Nullam ex metus, mollis eget dignissim quis, bibendum et mauris. Integer bibendum, lacus sit amet tincidunt aliquam, sapien arcu tempor nisi, eget egestas massa felis ut purus. Nulla a purus a nisl tincidunt scelerisque. Proin tempor arcu et tortor lacinia, ac pellentesque eros consectetur. Aenean eget eros in lectus auctor finibus ac nec ex.</p>
            </div>
          </div>
        </div>
        <div id="mask"></div>
</section>
<div class="bottom_bar"><span class="text">Estás recargando: </span>
    <div class="select"><span></span>
        <select name="tarjeta" id="tarjeta">
            <?php foreach ($usuarioTarjetas as $codigo => $nombre) : ?>
            <?php $select = ($codigo == $tarjetaCodigo) ? 'selected="selected"' : ''; ?>
            <option value="<?php echo $codigo; ?>" <?php echo $select; ?>><?php echo $nombre; ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <?php $cantidad = empty($cartModel) ? '0' : $cartModel->getQuantityGroup(); ?>
    <?php $monto = empty($cartModel) ? '0.00' : $cartModel->getAmountGroup(true); ?>
    <span class="bg" id="spanSubtotal"> <span class="text">Recargas: </span><?php echo $cantidad; ?> <span>/ </span>S/. <?php echo $monto; ?></span>
    <span class="text">Monto total: </span>
    <?php $montoTotal = empty($cartModel) ? '0.00' : $cartModel->getAmountCart(true); ?>
    <span class="bg total" id="spanTotal">S/. <?php echo $montoTotal; ?></span><button id="confirmarCompra" class="btn btn_orange">Confirmar compra </button>
</div>
<div class="bg_purple_dark"></div>
<style>
    footer{
        background: #370135;
    }
</style>

<script type="text/javascript" >
    var cart = {
        bloquear:0,
        seleccionarTarjeta:function(codigo)
        {
            location.href= baseUrl+'recargas/'+codigo;
        },
        confirmarCompra:function()
        {
            location.href= baseUrl+'carrito/pagos';
        },
        sendCart:function(prefix)
        {
            var result = false;
            cart.bloquear = 1;
            $.ajax({
                type: "POST",
                url: '<?php echo BASE_URL; ?>carrito/modificar',
                data:{id:$('#id_'+prefix).val(), cantidad:$('#cantidad_'+prefix).val(), tarjeta:$('#tarjeta').val()},
                dataType: 'json',
                async:false,
                success: function(data){
                    if (data.success) {
                        $('#spanSubtotal').html(' <span class="text">Recargas: </span>'+data.data.cantidad+' <span>/ </span>S/. '+data.data.subtotal);
                        $('#spanTotal').html('S/. '+data.data.total);
                        $('#spanCantidadTotal').html(data.data.cantidadTotal);
                        result = true;
                    }
                    cart.bloquear = 0;
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    cart.bloquear = 0;
                }
            });
            
            return result;
        },
        agregar:function(prefix){
            var cantidad = $('#cantidad_'+prefix).val();
            cantidad = ($.trim(cantidad).length < 1) ? 0 : parseInt(cantidad);
            var newCantidad = cantidad >= 5 ? 5 : (cantidad + 1);
            $('#cantidad_'+prefix).val(newCantidad);
            cart.sendCart(prefix);
        },
        remover:function(prefix) {
            var cantidad = $('#cantidad_'+prefix).val();
            cantidad = ($.trim(cantidad).length < 1) ? 0 : parseInt(cantidad);
            var newCantidad = cantidad < 1 ? 0 : (cantidad - 1);
            $('#cantidad_'+prefix).val(newCantidad);
            cart.sendCart(prefix);
        },
        init:function() {
            $('.less').each(function(){
                $(this).click(function(){
                    cart.remover($(this).parent().data('prefix'));
                });
            });
            $('.more').each(function(){
                $(this).click(function(){
                    cart.agregar($(this).parent().data('prefix'));
                });
            });
            $('input.cant').each(function(){
                $(this).change(function(){
                    cart.sendCart($(this).parent().data('prefix'));
                });
            });
            $('#tarjeta').change(function(){
               cart.seleccionarTarjeta($(this).val());
            });
            $('#confirmarCompra').click(function(){
               cart.confirmarCompra();
            });
        }
    };
    $(document).ready(function (){
        cart.init();
    });
</script>