<section class="app_content recargas">
    <?php $tarjetaProductos = empty($cartModel) ? array() : $cartModel->getProductsGroup(); ?>
    <?php echo $this->sectionPromocionesYRecargas($cartModel, $tarjetaProductos);  ?>
    <div id="mask"></div>
</section>
<div class="bottom_bar">
    <div class="box_mobile">
        <span class="icon_arrow"></span>
        <span class="text">Estás recargando: </span>
        <div class="select"><span></span>
            <select name="tarjeta" id="tarjeta">
                <?php foreach ($usuarioTarjetas as $codigo => $nombre) : ?>
                <?php $select = ($codigo == $tarjetaCodigo) ? 'selected="selected"' : ''; ?>
                <option value="<?php echo $codigo; ?>" <?php echo $select; ?>><?php echo $nombre; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <?php $cantidad = empty($cartModel) ? '0' : $cartModel->getQuantityGroup(); ?>
        <?php $monto = empty($cartModel) ? '0.00' : $cartModel->getAmountGroup(true); ?>
        <span class="bg hide" id="spanSubtotal"> <span class="text">Recargas: </span><?php echo $cantidad; ?> <span>/ </span>S/. <?php echo $monto; ?></span>
        <span class="text hide">Monto total: </span>
        <?php $montoTotal = empty($cartModel) ? '0.00' : $cartModel->getAmountCart(true); ?>
        <span class="bg total hide" id="spanTotal">S/. <?php echo $montoTotal; ?></span><button id="confirmarCompra" class="btn btn_orange hide">Confirmar compra </button>
    </div>
    
</div>
<div class="bg_purple_dark"></div>
<style>
    footer{
        background: #370135;
    }
</style>

<script type="text/javascript" >
    var cart = {
        bloquear:0,
        seleccionarTarjeta:function(codigo)
        {
            location.href= baseUrl+'recargas/'+codigo;
        },
        confirmarCompra:function()
        {
            location.href= baseUrl+'carrito/pagos';
        },
        sendCart:function(prefix)
        {
            var result = false;
            cart.bloquear = 1;
            $.ajax({
                type: "POST",
                url: '<?php echo BASE_URL; ?>carrito/modificar',
                data:{id:$('#id_'+prefix).val(), cantidad:$('#cantidad_'+prefix).val(), tarjeta:$('#tarjeta').val()},
                dataType: 'json',
                async:false,
                success: function(data){
                    if (data.success) {
                        $('#spanSubtotal').html(' <span class="text">Recargas: </span>'+data.data.cantidad+' <span>/ </span>S/. '+data.data.subtotal);
                        $('#spanTotal').html('S/. '+data.data.total);
                        $('#spanCantidadTotal').html(data.data.cantidadTotal);
                        result = true;
                    }
                    cart.bloquear = 0;
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    cart.bloquear = 0;
                }
            });
            
            return result;
        },
        agregar:function(prefix){
            var cantidad = $('#cantidad_'+prefix).val();
            cantidad = ($.trim(cantidad).length < 1) ? 0 : parseInt(cantidad);
            var newCantidad = cantidad >= 5 ? 5 : (cantidad + 1);
            $('#cantidad_'+prefix).val(newCantidad);
            cart.sendCart(prefix);
        },
        remover:function(prefix) {
            var cantidad = $('#cantidad_'+prefix).val();
            cantidad = ($.trim(cantidad).length < 1) ? 0 : parseInt(cantidad);
            var newCantidad = cantidad < 1 ? 0 : (cantidad - 1);
            $('#cantidad_'+prefix).val(newCantidad);
            cart.sendCart(prefix);
        },
        init:function() {
            $('.less').each(function(){
                $(this).click(function(){
                    cart.remover($(this).parent().data('prefix'));
                });
            });
            $('.more').each(function(){
                $(this).click(function(){
                    cart.agregar($(this).parent().data('prefix'));
                });
            });
            $('input.cant').each(function(){
                $(this).on( 'keydown' , function(){
                    if($(this).val() > 5){
                        $(this).val("5");
                    }
                });
                $(this).on( 'keyup' , function(){
                    if($(this).val() > 5){
                        $(this).val("5");
                    }
                });
                $(this).change(function(){
                    cart.sendCart($(this).parent().data('prefix'));
                });
            });
            $('#tarjeta').change(function(){
               cart.seleccionarTarjeta($(this).val());
            });
            $('#confirmarCompra').click(function(){
               cart.confirmarCompra();
            });
        }
    };
    $(document).ready(function (){
        cart.init();
    });
</script>