<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <style type="text/css" media="screen">
            body {
                background-color: #FFFFFF;
                margin: 0;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            }

            .container { margin: 0px auto 40px auto; width: auto; text-align: center; }
            .message { margin: 50px auto 40px auto; width: 600px; text-align: center; }

            a { color: #4183c4; text-decoration: none; }
            a:hover { text-decoration: underline; }

            h1 { width: 800px; position:relative; left: -100px; letter-spacing: -1px; line-height: 60px; font-size: 60px; font-weight: 100; margin: 0px 0 50px 0; text-shadow: 0 1px 0 #fff; }
            p { color: rgba(0, 0, 0, 0.5); margin: 20px 0; line-height: 1.6; }

            ul { list-style: none; margin: 25px 0; padding: 0; }
            li { display: table-cell; font-weight: bold; width: 1%; }

            .logo { display: inline-block; margin-top: 35px; }
            .logo-img-2x { display: none; }
            @media
            only screen and (-webkit-min-device-pixel-ratio: 2),
            only screen and (   min--moz-device-pixel-ratio: 2),
            only screen and (     -o-min-device-pixel-ratio: 2/1),
            only screen and (        min-device-pixel-ratio: 2),
            only screen and (                min-resolution: 192dpi),
            only screen and (                min-resolution: 2dppx) {
                .logo-img-1x { display: none; }
                .logo-img-2x { display: inline-block; }
            }

            #suggestions {
                margin-top: 35px;
                color: #ccc;
            }
            #suggestions a {
                color: #666666;
                font-weight: 200;
                font-size: 14px;
                margin: 0 10px;
            }
            .logo_ec {
                /*background: url("<?php //echo $this->constant('url.domain') ?>img/eco-logo.png") no-repeat scroll 0 1px rgba(0, 0, 0, 0);*/
                color: #FFFFFF;
                height: 21px;
                line-height: 1.5em;
                padding-left: 125px;
            }
            .header_logo {
                font-family: "Lucida Sans Unicode","Lucida Console","Lucida Grande",sans-serif;
                font-size: 24px;
                font-weight: normal;
                margin-bottom: 15px;
            }
            .header_logo_mod {
                color: #313131;
            }
            .header_logo_eco {
                color: #FFCC00;
            }
            .sec_eco_cla {
                background-color: #2F322E;
                border-bottom: 1px solid #FFCC00;
                border-top: 1px solid #656461;
                height: 21px;
            }
            .wrapper, .w100 {
                display: block;
                width: 100% !important;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="wrapper sec_eco_cla">
                <a target="_blank" href="http://elcomercio.pe"><div class="logo_ec">&nbsp;</div></a>
            </div>
            <div class="message">
                <div class="header_logo">
                    <span class="header_logo_eco">CONEYPARK - TS</span>                    
                </div>
                <?php echo $this->content; ?>
            </div>
        </div>
    </body>
</html>
