<?php
$this->layout()->breadcrumb = array(
    array('url' => null, 'name' => 'Contenido'),
    array('url' => null, 'name' => 'Listado'),
);
?>

<div class="box">
    <div class="box-header with-border">
        <?php echo $this->partial('admin/contenido/_buscar.phtml', array('form' => $form)); ?>
    </div>
    <div class="box-body">
        <?php echo $this->showMessenger($this->flashMessenger()->getMessages()); ?>
        <a href="<?php echo BASE_URL; ?>admin/contenido/crear" class="btn btn-success">Crear</a>
        <hr class="separator">
        <table id="gridMain" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Codigo</th>
                    <th>Tipo</th>
                    <th>Titulo</th>
                    <th>Url</th>
                    <th>Estado</th>
                    <th style="max-width: 60px"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($gridList as $row) : ?>
                    <tr>
                        <td><?php echo $row['codigo'] ?></td>
                        <td><?php echo \Cms\Model\Service\ContenidoService:: getNameTipo($row['tipo']); ?></td>
                        <td><?php echo $row['titulo'] ?></td>
                        <td><a target="_blank" href="<?php echo $row['url']; ?>"><?php echo $row['url']; ?></a></td>
                        <td><?php echo (!empty($row['estado']))? 'Activo': 'Baja'; ?></td>
                        <td>
                            <a href="<?php echo BASE_URL ?>admin/contenido/editar/<?php echo $row['id']; ?>" class="btn btn-primary" title="Editar"><i class="fa fa-edit"></i></a>
                            <a href="<?php echo BASE_URL ?>admin/contenido/eliminar/<?php echo $row['id']; ?>" class="btn btn-danger delete-remote" title="Eliminar"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#gridMain').DataTable({
            "pageLength": 25,
            "paging": true,
            "lengthChange": true,
            "searching": false,
            "ordering": false,
            "language": {
                "info": "Registros de _START_ al _END_, de un total de <?php echo $countList; ?>"
            },
            "autoWidth": true
        });
        common.deleteRemote();
    });
</script>