<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Coneypark</title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body class="cc-notbg">
        <div class="main">
            <header>
                <div class="cc-orderheader">
                    <h1><span></span>Error</h1>					
                </div>
            </header>
            <div class="container-fluid">
                <?php echo $this->content; ?>
            </div>
        </div>
    </body>
</html>