<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Coneypark</title>
        
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="<?php echo URL_RESOURCES; ?>b/adminlte/plugins/jQuery/jQuery-2.1.4.min.js?v=<?php echo VERSION; ?>"></script>
    </head>
    <body class="cc-notbg">
        <div class="main">
            <div class="container-fluid">
                <div class="col-md-10 col-sm-10">
                    <div class="container-fluid cc-left">
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>            
        </div>
    </body>
</html>