<html>
    <head>
        <title>Coney Park</title>
        <meta name="description" content="Welcome"/>
        <meta charset="UTF-8">
        <link rel="shortcut icon" href="<?php echo URL_RESOURCES ?>front/dist/images/favicon.png" type="image/x-icon" />
        <link rel="stylesheet" href="<?php echo URL_RESOURCES ?>front/dist/css/normalize.css?v=<?php echo VERSION_STATICO; ?>"/>
        <link rel="stylesheet" href="<?php echo URL_RESOURCES ?>front/dist/css/style.css?v=<?php echo VERSION_STATICO; ?>"/>
        <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
        <script>var baseUrl = '<?php echo BASE_URL; ?>';</script>
    </head>
    <body>
        <?php echo $this->sectionHeader(); ?>
        <?php echo $this->sectionRightOption(); ?>
        <?php echo $this->content; ?>
        <?php echo $this->sectionFooter(); ?>
        <!--JS-->
        <script src="<?php echo URL_RESOURCES ?>front/dist/js/plugins/parsley.min.js"></script>
        <script src="<?php echo URL_RESOURCES ?>front/dist/js/app.index.js?v=<?php echo VERSION_STATICO; ?>"></script>
    </body>
</html>