<?php $this->form->prepare(); ?>
<div class="box">
    <div class="box-header with-border">
        <label>Rol</label>
    </div>
    <?php echo $this->form()->openTag($this->form->setAttribute('class', 'form-horizontal')); ?>
    <div class="box-body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="nombre">Nombre <span>*</span></label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('nombre')->setAttribute('class', 'form-control')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('nombre')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="estado">Estado</label>
            <div class="col-sm-8">
                <?php echo $this->formElement($this->form->get('estado')) ?>
                <span class="error"><?php echo $this->formElementerrors($form->get('estado')); ?></span>
            </div>
        </div>
        <div class="box-footer">
            <a class="btn btn-default" href="<?php echo BASE_URL; ?>admin/rol/index">Regresar</a>
            <button class="btn btn-success" type="submit">Aceptar</button>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>