<section>
    <div class="box_center">
        <div class="welcome_box signin_complete">
            <div class="yellow_box">Mis datos</div>
            <div class="purple_box">
                <?php $flashMessage = $this->flashMessenger()->getMessages(); ?>
                <?php if (count($flashMessage) > 0) : ?>
                    <?php foreach ($flashMessage as $msg) : ?>
                        <?php foreach ($msg as $type => $message) : ?>
                            <div class="<?php echo $type; ?>_message"><span class="icon"></span><span class="text"><?php echo $message; ?></span></div>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php echo $this->form()->openTag($this->form->setAttributes(array('class' => 'signin_form form_mis_datos', 'data-parsley-validate' => 'data-parsley-validate'))); ?>
                <?php  $this->formElementerrors()->setMessageOpenFormat('<ul class="parsley-errors-list filled"><li class="parsley-required">')->setMessageCloseString('</li></ul>'); ?>
                    <h3>Tus datos de cuenta</h3>
                    <div class="content_form">
                        <div class="form_control">
                            <label class="left">Imagen de perfil</label>
                            <div class="right">
                                <div class="left user_image_left">
                                    <div class="image">
                                        <img id="img_imagen" width="88" height="88" src="<?php echo $urlImg . '/' . $imagen; ?>" onerror="this.src='<?php echo $urlImg . '/user-web-default.png'; ?>';" alt="Mi foto"/>
                                    </div>
                                </div>
                                <div class="right user_image_right">
                                    <?php echo $this->formElement($this->form->get('imagen')->setAttributes(array('class' => 'image_file'))); ?><span class="btn change_user_image">Actualizar imagen</span>
                                    <?php echo $this->formElementerrors($form->get('imagen')); ?>
                                    <p class="image_info">La imagen debe pesar como máximo 1000 KB. Formatos permitidos: JPG, PNG </p>
                                </div>
                            </div>
                        </div>
                        <div class="form_control">
                            <label class="left" for="email">Correo</label>
                            <div class="right">
                                <?php echo $this->formElement($this->form->get('email')->setAttributes(array(
                                    'class' => 'disabled',
                                    'data-parsley-required' => 'true',
                                    'data-parsley-required-message' => 'Este campo es requerido y no puede estar vacío'
                                ))) ?>
                                <?php echo $this->formElementerrors($form->get('email')); ?>
                            </div>
                        </div>
                        <div class="form_control">
                            <label class="left" for="password">Contraseña</label>
                            <div class="right">
                                <?php echo $this->formElement($this->form->get('password')->setAttributes(array(
                                    'class' => '',
                                    //'data-parsley-required' => 'true',
                                    //'data-parsley-required-message' => 'Este campo es requerido y no puede estar vacío'
                                ))) ?>
                                <?php echo $this->formElementerrors($form->get('password')); ?>
                            </div>
                        </div>
                        <div class="form_control">
                            <label class="left" for="password_repeat">Repetir contraseña</label>
                            <div class="right">
                                <?php echo $this->formElement($this->form->get('password_repeat')->setAttributes(array(
                                    'class' => '',
                                    //'data-parsley-required' => 'true',
                                    //'data-parsley-required-message' => 'Este campo es requerido y no puede estar vacío'
                                ))) ?>
                                <?php echo $this->formElementerrors($form->get('password_repeat')); ?>
                                <span class="pass_info">Si no deseas modificar tu contraseña, déjalo vacío</span>
                            </div>
                        </div>
                    </div>
                    <div class="bg_purple_change_email">

                        <p>Si haz cambiado de cuenta de correo electrónico o deseas
                            actualizar algún dato personal <a href="http://coneypark.pe/contactos" target="_blank">contáctanos</a> para ayudarte a actualizarlo.</p>
                    </div>
                    <h3>Tus datos personales</h3>
                    <div class="content_form">
                        <div class="form_control">
                            <label class="left" for="nombres">Nombre</label>
                            <div class="right">
                                <?php echo $this->formElement($this->form->get('nombres')->setAttributes(array(
                                    'class' => 'disabled',
                                    'data-parsley-required' => 'true',
                                    'data-parsley-required-message' => 'Este campo es requerido y no puede estar vacío'
                                ))) ?>
                                <?php echo $this->formElementerrors($form->get('nombres')); ?>
                            </div>
                        </div>
                        <div class="form_control">
                            <label class="left" for="paterno">Apellido paterno</label>
                            <div class="right">
                                <?php echo $this->formElement($this->form->get('paterno')->setAttributes(array(
                                    'class' => 'disabled',
                                    'data-parsley-required' => 'true',
                                    'data-parsley-required-message' => 'Este campo es requerido y no puede estar vacío'
                                ))) ?>
                                <?php echo $this->formElementerrors($form->get('paterno')); ?>
                            </div>
                        </div>
                        <div class="form_control">
                            <label class="left" for="materno">Apellido materno</label>
                            <div class="right">
                                <?php echo $this->formElement($this->form->get('materno')->setAttributes(array(
                                    'class' => 'disabled',
                                    'data-parsley-required' => 'true',
                                    'data-parsley-required-message' => 'Este campo es requerido y no puede estar vacío'
                                ))) ?>
                                <?php echo $this->formElementerrors($form->get('materno')); ?>
                            </div>
                        </div>
                        <div class="form_control">
                            <label class="left" for="di_valor">Documento de identidad</label>
                            <div class="right">
                                <div class="bg_white doc_type">
                                    <?php echo $this->formElement($this->form->get('di_tipo')->setAttributes(array(
                                        'class' => 'disabled',
                                    ))) ?>
                                </div>
                                <?php echo $this->formElement($this->form->get('di_valor')->setAttributes(array(
                                        'class' => 'inp_right disabled',
                                        'placeholder' => 'Nro de documento',
                                        'data-parsley-required' => 'true',
                                        'data-parsley-required-message' => 'Este campo es requerido y no puede estar vacío'
                                    ))) ?>
                            </div>
                            <div class="right">
                            <?php echo $this->formElementerrors($form->get('di_valor')); ?>
                            </div>
                        </div>
                        <div class="form_control">
                            <label class="left" for="departamento_id">Departamento</label>
                            <div class="right bg_white">
                                <?php echo $this->formElement($this->form->get('departamento_id')->setAttributes(array(
                                    'class' => 'right',
                                ))) ?>
                            </div>
                            <div class="right error_message_dep">
                                <?php echo $this->formElementerrors($form->get('departamento_id')); ?>
                            </div>
                        </div>
                        <div class="form_control">
                            <label class="left" for="provincia_id">Provincia</label>
                            <div class="right bg_white">
                                <?php echo $this->formElement($this->form->get('provincia_id')->setAttributes(array(
                                    'class' => 'right',
                                ))) ?>
                                
                            </div>
                            <div class="right error_message_pro">
                                <?php echo $this->formElementerrors($form->get('provincia_id')); ?>
                            </div>
                        </div>
                        <div class="form_control">
                            <label class="left" for="distrito_id">Distrito</label>
                            <div class="right bg_white">
                                <?php echo $this->formElement($this->form->get('distrito_id')->setAttributes(array(
                                    'class' => 'right',
                                ))) ?>
                            </div>
                            <div class="right error_message_dis">
                                <?php echo $this->formElementerrors($form->get('distrito_id')); ?>
                            </div>
                        </div>
                        <div class="form_control">
                            <label class="left">Fecha de nacimiento</label>
                            <div class="right">
                                <div class="day bg_white">
                                    <?php echo $this->formElement($this->form->get('dia')->setAttributes(array(
                                        'class' => '',
                                    ))) ?>
                                </div>
                                <div class="month bg_white">
                                    <?php echo $this->formElement($this->form->get('mes')->setAttributes(array(
                                        'class' => '',
                                    ))) ?>
                                </div>
                                <div class="year bg_white">
                                    <?php echo $this->formElement($this->form->get('anio')->setAttributes(array(
                                        'class' => '',
                                    ))) ?>
                                </div>
                            </div>
                            <div class="right">
                                <?php echo $this->formElementerrors($form->get('dia')); ?>
                            </div>
                        </div>
                        <div class="form_control">
                            <div class="right">
                                <?php echo $this->formRow($form->get('token_csrf')); ?>
                                <button type="submit" class="btn btn_orange btn_save_signin btn_save_dates">Actualizar mis datos</button>
                            </div>
                        </div>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</section>
<script type="text/javascript">
    function previewImage() {
        var _validFileExtensions = [".jpg", ".jpeg", ".png"];
        var sValue = document.getElementById("imagen").value;
        if (sValue.length > 0) {
            var blnValid = false; 
            for (var j = 0; j < _validFileExtensions.length; j++) {
                var sCurExtension = _validFileExtensions[j];
                if (sValue.substr(sValue.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                    blnValid = true;
                    break;
                }
            }
            if (!blnValid) {
                alert("Sólo se permiten archivos con extensión " + _validFileExtensions.join(", "));
                return false;
            }
        }
        
        
        var oFReader = new FileReader();
        oFReader.readAsDataURL(document.getElementById("imagen").files[0]);

        oFReader.onload = function (oFREvent) {
            document.getElementById("img_imagen").src = oFREvent.target.result;
        };
    }
    $(document).ready(function(){
        $('#imagen').change(function(){previewImage();});
    });
</script>
<script type="text/javascript">
    var ubigeo = {
        loadProvincia:function(){
            $.ajax({
                type: "GET",
                url: '<?php echo BASE_URL; ?>application/ubigeo/provincia',
                data:{departamento_id:$('#departamento_id').val()},
                dataType: 'json',
                success: function(data){
                    var htmlDdl = '<option value="">- Seleccione -</option>';
                    for (var key in data) {
                        htmlDdl = htmlDdl+'<option value="'+key+'">'+data[key]+'</option>';
                    }
                    $('#provincia_id').html(htmlDdl);
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) { 
                }
            });
        },
        loadDistrito:function(){
            $.ajax({
                type: "GET",
                url: '<?php echo BASE_URL; ?>application/ubigeo/distrito',
                data:{provincia_id:$('#provincia_id').val()},
                dataType: 'json',
                success: function(data){
                    var htmlDdl = '<option value="">- Seleccione -</option>';
                    for (var key in data) {
                        htmlDdl = htmlDdl+'<option value="'+key+'">'+data[key]+'</option>';
                    }
                    $('#distrito_id').html(htmlDdl);
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) { 
                }
            });
        }
    };
    
    $(document).ready(function(){
        $('#departamento_id').change(function(){ubigeo.loadProvincia();});
        $('#provincia_id').change(function(){ubigeo.loadDistrito();});
    });
</script>