<?php $this->layout()->title = array('Mi perfil', 'Modificar') ?>
<?php
$this->layout()->breadcrumb = array(
    array('url' => null, 'name' => 'Mi perfil'),
    array('url' => null, 'name' => 'Modificar'),
);
?>
<?php echo $this->showMessenger($this->flashMessenger()->getMessages()); ?>
<?php echo $this->partial('admin/usuarioadmin/_form.phtml', array('form' => $form, 'repeat' => true, 'noRegresar' => true)); ?>
