<section class="app_content">
    <div class="box_center">
        <div class="app_box">
            <div class="menu">
                <ul>
                    <li class="first"><a href="<?php echo BASE_URL; ?>beneficios">Beneficios</a></li>
                    <li class="active"><a href="<?php echo BASE_URL; ?>mis-tarjetas">Mis tarjetas</a></li>
                    <li class="last"><a href="<?php echo BASE_URL; ?>recargas">Recargas</a></li>
                </ul>
            </div>
            <div class="purple_box">
                <p class="yellow_text small_text">Mis tarjetas asociadas</p>
                <div class="cards_content">
                    <?php $index = 0; ?>
                    <?php foreach ($gridList as $key => $row) : ?>
                        <?php if ($row['show'] == 'lleno') : ?>
                            <?php $index++; ?>
                            <div class="col_3 my_card" id="init_card_<?php echo $index; ?>">
                                <div class="meta_data" data-index="<?php echo $index; ?>" data-codigo="<?php echo $row['codigo'] ?>" data-cguid="<?php echo $row['cguid'] ?>" data-numero="<?php echo $row['numero'] ?>" data-nombre="<?php echo $row['nombre'] ?>" style="display: none;"></div>
                                <div class="init_loading"><img src="<?php echo URL_RESOURCES ?>front/images/loading.gif" alt="Cargando..."/></div>
                            </div>
                        <?php elseif ($row['show'] == 'por_llenar') : ?>
                            <div class="col_3 add_card">
                                <div class="show_tooltip">
                                    <div class="tooltip"><strong>Para iniciar una recarga</strong>, es importante que asocies una tarjeta. Con ella podrás recargar todas las promociones y |recargas que desees. ¡Puedes tener hasta 6 tarjetas!</div>
                                </div>
                                <div class="content_asociate_card">
                                    <form id="form_asociar_nueva_tarjeta" action="<?php echo BASE_URL ?>mis-tarjetas/asociar-nueva-tarjeta" data-parsley-validate="true" class="asociate_form">
                                        <input id="numero" name="numero" type="text" placeholder="Ingresa tu número de tarjeta" data-parsley-required="data-parsley-required" data-parsley-required-message="Este campo es requerido." class="card_number"/>
                                        <input id="nombre" name="nombre" type="text" placeholder="¡Nombra tu tarjeta!" data-parsley-required="data-parsley-required" data-parsley-required-message="Este campo es requerido." class="card_name"/>
                                        <button type="submit" class="btn btn_orange btn_asociate_card">Asociar tarjeta</button>
                                    </form>
                                    <div class="link_orange btn_cancel">Cancelar	</div>
                                </div>
                                <div class="loading"><img src="<?php echo URL_RESOURCES ?>front/images/loading.gif" alt="Cargando..."/></div>
                                <div class="success_box"><span class="icon"></span>
                                    <h3>¡Tarjeta asociada!</h3><a href="">Conocer los beneficios</a>
                                </div>
                                <div class="error_box"><span class="icon"></span>
                                    <p>Lo sentimos, no se pudo completar el proceso, por favor inténtalo más tarde</p><a href="">Aceptar</a>
                                </div>
                                <div class="duplicate_box"><span class="icon"></span>
                                  <p>El nombre <strong>"Ahijado-tarjeta" </strong>ya se encuentra en tu lista de tarjetas</p><a href="">Aceptar</a>
                                </div>
                            </div>
                        <?php else : ?>
                            <div class="col_3 empty"></div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
                <hr/>
                <div class="info_box"><span class="icon"></span><span class="text">También puedes acercarte a cualquier local de lunes a jueves indicando tu cuenta de correo electrónico y mostrando la tarjeta que deseas recargar.</span><a href="#how_asociate_card" name="modal" class="how_asociate_card">¿Cómo asociar mis tarjetas?</a></div>
            </div>
        </div>
        
    </div>
    <div id="how_asociate_card" class="modal_box">
          <div class="modal_content"><span class="icon_logo"></span>
            <h3>Para asociar tus tarjetas, sigue los siguientes pasos: <span></span></h3>
            <hr/>
            <p>1. Encuentra el número de <strong>10 dígitos </strong>en tu tarjeta física</p><img src="<?php echo URL_RESOURCES ?>front/dist/images/card_detail.png" alt=""/>
            <p>2. Ingresa el número y asignarle el nombre que más prefieras</p><img src="<?php echo URL_RESOURCES ?>front/dist/images/signin_form.png" alt=""/>
          </div>
        </div>
        <div id="mask"></div>
</section>
<script type="text/javascript">
    var totalInitTarjeta = parseInt('<?php echo $index; ?>');
    function getCard(index)
    {
        var _this = $('#init_card_'+index);
        $.ajax({
            type: "GET",
            url: baseUrl + 'mis-tarjetas/tarjeta-unidad',
            data: {index:_this.children('.meta_data').data('index'), codigo:_this.children('.meta_data').data('codigo'), cguid:_this.children('.meta_data').data('cguid'), numero:_this.children('.meta_data').data('numero'), nombre:_this.children('.meta_data').data('nombre'), destino:_this.attr('id')},
            dataType:'json',
            success: function(data) {
                if (data.success) {
                    $('#'+data.data.destino).html(data.data.html);
                    if (index < totalInitTarjeta) {
                        getCard(index+1);
                    }
                }
            },
            error: function(XMLHttpRequest, textStatus, errorThrown) {
            }
        });
    }
    $(document).ready(function(){

        if (totalInitTarjeta > 0) {
            getCard(1);
        }
    });
</script>