<section class="app_content">
    <div class="box_center">
        <div class="app_box">
            <div class="menu">
                <ul>
                    <li class="first">Beneficios</li>
                    <li class="active">Mis tarjetas</li>
                    <li class="last">Recargas</li>
                </ul>
            </div>
            <div class="purple_box">
                <p class="yellow_text small_text">Mis tarjetas asociadas</p>
                <div class="cards_content">
                    <div class="col_3 my_card">
                        <div class="top_card"><span class="cp_logo"></span>
                            <div class="card_title">
                                <input type="text" class="input_name"/><span class="text">Tarjeta de Maria Emilia</span><span class="edit_icon"></span>
                            </div><span class="card_number">000 - 00000003 - 89</span>
                        </div>
                        <div class="show_more_content">
                            <div class="line">
                                <div class="left">Coney Bonos<span>?</span></div>
                                <div class="right">S/.30</div>
                                <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                            </div>
                            <div class="line">
                                <div class="left">Coney Bonos Plus<span>?</span></div>
                                <div class="right">S/.15</div>
                                <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                            </div>
                            <div class="line">
                                <div class="left">Tickets<span>?</span></div>
                                <div class="right">12</div>
                                <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                            </div>
                            <div class="line">
                                <div class="left">Gamepoints<span>?</span></div>
                                <div class="right">12</div>
                                <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                            </div>
                        </div>
                        <div class="bottom_card">
                            <div class="price">S/. 30.00</div><a href="javascript:;" class="watch_more">Ver más</a><a href="" class="recharge">Recargar</a>
                        </div>
                    </div>
                    <div class="col_3 my_card">
                        <div class="top_card"><span class="cp_logo"></span>
                            <div class="card_title">
                                <input type="text" class="input_name"/><span class="text">Tarjeta de Rosa</span><span class="edit_icon"></span>
                            </div><span class="card_number">000 - 00000003 - 89</span>
                        </div>
                        <div class="show_more_content">
                            <div class="line">
                                <div class="left">Coney Bonos<span>?</span></div>
                                <div class="right">S/.30</div>
                                <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                            </div>
                            <div class="line">
                                <div class="left">Coney Bonos Plus<span>?</span></div>
                                <div class="right">S/.15</div>
                                <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                            </div>
                            <div class="line">
                                <div class="left">Tickets<span>?</span></div>
                                <div class="right">12</div>
                                <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                            </div>
                            <div class="line">
                                <div class="left">Gamepoints<span>?</span></div>
                                <div class="right">12</div>
                                <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                            </div>
                        </div>
                        <div class="bottom_card">
                            <div class="price">S/. 30.00</div><a href="javascript:;" class="watch_more">Ver más</a><a href="" class="recharge">Recargar</a>
                        </div>
                    </div>
                    <div class="col_3 my_card">
                        <div class="top_card"><span class="cp_logo"></span>
                            <div class="card_title">
                                <input type="text" class="input_name"/><span class="text">Tarjeta de Fernando</span><span class="edit_icon"></span>
                            </div><span class="card_number">000 - 00000003 - 89</span>
                        </div>
                        <div class="show_more_content">
                            <div class="line">
                                <div class="left">Coney Bonos<span>?</span></div>
                                <div class="right">S/.30</div>
                                <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                            </div>
                            <div class="line">
                                <div class="left">Coney Bonos Plus<span>?</span></div>
                                <div class="right">S/.15</div>
                                <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                            </div>
                            <div class="line">
                                <div class="left">Tickets<span>?</span></div>
                                <div class="right">12</div>
                                <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                            </div>
                            <div class="line">
                                <div class="left">Gamepoints<span>?</span></div>
                                <div class="right">12</div>
                                <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                            </div>
                        </div>
                        <div class="bottom_card">
                            <div class="price cero">S/. 0.00</div><a href="javascript:;" class="watch_more">Ver más</a><a href="" class="recharge">Recargar</a>
                        </div>
                    </div>
                    <div class="col_3 add_card">
                        <div class="show_tooltip">
                            <div class="tooltip"><strong>Para iniciar una recarga</strong>, es importante que asocies una tarjeta. Con ella podrás recargar todas las promociones y |recargas que desees. ¡Puedes tener hasta 6 tarjetas!</div>
                        </div>
                        <div class="content_asociate_card">
                            <form action="" data-parsley-validate="true" class="asociate_form">
                                <input type="text" placeholder="Ingresa tu número de tarjeta" data-parsley-required="data-parsley-required" data-parsley-required-message="Dato obligatorio" class="card_number"/>
                                <input type="text" placeholder="¡Nombra tu tarjeta!" data-parsley-required="data-parsley-required" data-parsley-required-message="Dato obligatorio" class="card_name"/>
                                <button type="submit" class="btn btn_orange btn_asociate_card">Asociar tarjeta</button>
                            </form>
                            <div class="link_orange btn_cancel">Cancelar	</div>
                        </div>
                        <div class="loading"><img src="../images/loading.gif" alt=""/></div>
                        <div class="success_box"><span class="icon"></span>
                            <h3>¡Tarjeta asociada!</h3><a href="">Conocer los beneficios</a>
                        </div>
                        <div class="error_box"><span class="icon"></span>
                            <p>Lo sentimos, no se pudo completar el proceso, por favor inténtalo más tarde</p><a href="">Aceptar</a>
                        </div>
                    </div>
                    <div class="col_3"></div>
                    <div class="col_3"></div>
                </div>
                <hr/>
                <div class="info_box"><span class="icon"></span><span class="text">Recuerda que también puedes acercarte a cualquiera de nuestras sedes, indicando tu cuenta de correo electrónico junto con la tarjeta que desees asociar.</span><a href="#how_asociate_card" name="modal" class="how_asociate_card">¿Cómo asociar mis tarjetas?</a></div>
            </div>
        </div>
        <div id="how_asociate_card" class="modal_box">
            <div class="modal_content"><span class="icon_logo"></span>
                <h3>Para asociar tus tarjetas, sigue los siguientes pasos:</h3>
                <hr/>
                <p>1. Encuentra el número de <strong>10 dígitos </strong>en tu tarjeta física</p>
                <p>2. Ingresa el número (sin guíones) y asignarle el nombre que más prefieras</p>
                <input type="text" placeholder="Correo electrónico"/><a id="btn_recovery" href="#modal_recovery_response" name="modal" class="btn btn_orange">Recuperar contraseña</a>
            </div>
        </div>
        <div id="mask"></div>
    </div>
</section>



<!--<div>
    <?php foreach ($gridList as $row) : ?>
        <?php echo $row['nombre']; ?>
        <?php echo $row['numero']; ?>
        <?php echo $row['importe_emoney']; ?>
        <?php echo $row['importe_bonus']; ?>
        <br>
        <br>
    <?php endforeach; ?>
    <br>
    <br>
    <div id="nuevaTarjeta">
        <a class="asociar-nueva-tarjeta" href="<?php echo BASE_URL ?>inbox/mis-tarjetas/asociar-nueva-tarjeta">Asociar nueva tarjeta</a>
    </div>
</div>-->

<script type="text/javascript">
    function asociarNuevaTarjeta()
    {
        $('.asociar-nueva-tarjeta').click(function(e) {
            e.preventDefault();
            $.ajax({
                type: "GET",
                url: $(this).attr('href'),
                success: function(sHtml) {
                    $('#nuevaTarjeta').html(sHtml);
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    alert(common.ajaxError);
                }
            });
        });
    }
    function sendAsociarNuevaTarjeta()
    {
        $.ajax({
            type: "POST",
            url: $('#formAsociarNuevaTarjeta').attr('action'),
            dataType: 'json',
            success: function(data) {
                if (data.success) {
                    location.reload();
                }
            },
            error: function(XMLHttpRequest, textStatus, errorThrown) {
                alert(common.ajaxError);
            }
        });
    }

    $(document).ready(function() {
        asociarNuevaTarjeta();
    });
</script>