<section class="app_content">
    <div class="box_center">
        <div class="app_box">
            <div class="menu">
                <ul>
                    <li class="first"><a href="<?php echo BASE_URL; ?>beneficios">Beneficios</a></li>
                    <li class="active"><a href="<?php echo BASE_URL; ?>mis-tarjetas">Mis tarjetas</a></li>
                    <li class="last"><a href="<?php echo BASE_URL; ?>recargas">Recargas</a></li>
                </ul>
            </div>
            <div class="purple_box">
                <p class="yellow_text small_text">Mis tarjetas asociadas</p>
                <div class="cards_content">
                    <?php foreach ($gridList as $key => $row) : ?>
                        <?php if ($row['show'] == 1) : ?>
                            <div class="col_3 my_card">
                                <div class="top_card"><span class="cp_logo"></span>
                                    <div class="card_title">
                                        <input type="hidden" id="edit_numero_<?php echo $key; ?>" name="edit_numero_<?php echo $key; ?>" value="<?php echo $row['numero'] ?>"/>
                                        <input type="text" id="edit_nombre_<?php echo $key; ?>" name="edit_nombre_<?php echo $key; ?>" class="input_name"/>
                                        <span class="text"><?php echo $row['nombre'] ?></span>
                                        <span class="edit_icon" data-sufix="<?php echo $key; ?>"></span>
                                    </div>
                                    <span class="card_number"><?php echo $row['numero'] ?></span>
                                </div>
                                <div class="show_more_content">
                                    <div class="line">
                                        <div class="left">Coney Bonos<span>?</span></div>
                                        <div class="right">S/.30</div>
                                        <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                                    </div>
                                    <div class="line">
                                        <div class="left">Coney Bonos Plus<span>?</span></div>
                                        <div class="right">S/.15</div>
                                        <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                                    </div>
                                    <div class="line">
                                        <div class="left">Tickets<span>?</span></div>
                                        <div class="right">12</div>
                                        <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                                    </div>
                                    <div class="line">
                                        <div class="left">Gamepoints<span>?</span></div>
                                        <div class="right">12</div>
                                        <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
                                    </div>
                                </div>
                                <div class="bottom_card">
                                    <div class="price">S/. 30.00</div><a href="javascript:;" class="watch_more">Ver más</a><a href="" class="recharge">Recargar</a>
                                </div>
                            </div>
                        <?php elseif ($row['show'] == 2) : ?>
                            <div class="col_3 add_card">
                                <div class="show_tooltip">
                                    <div class="tooltip"><strong>Para iniciar una recarga</strong>, es importante que asocies una tarjeta. Con ella podrás recargar todas las promociones y |recargas que desees. ¡Puedes tener hasta 6 tarjetas!</div>
                                </div>
                                <div class="content_asociate_card">
                                    <form id="form_asociar_nueva_tarjeta" action="<?php echo BASE_URL ?>mis-tarjetas/asociar-nueva-tarjeta" data-parsley-validate="true" class="asociate_form">
                                        <input id="numero" name="numero" type="text" placeholder="Ingresa tu número de tarjeta" data-parsley-required="data-parsley-required" data-parsley-required-message="Este campo es requerido." class="card_number"/>
                                        <input id="nombre" name="nombre" type="text" placeholder="¡Nombra tu tarjeta!" data-parsley-required="data-parsley-required" data-parsley-required-message="Este campo es requerido." class="card_name"/>
                                        <button type="submit" class="btn btn_orange btn_asociate_card">Asociar tarjeta</button>
                                    </form>
                                    <div class="link_orange btn_cancel">Cancelar	</div>
                                </div>
                                <div class="loading"><img src="<?php echo URL_RESOURCES ?>front/images/loading.gif" alt=""/></div>
                                <div class="success_box"><span class="icon"></span>
                                    <h3>¡Tarjeta asociada!</h3><a href="">Conocer los beneficios</a>
                                </div>
                                <div class="error_box"><span class="icon"></span>
                                    <p>Lo sentimos, no se pudo completar el proceso, por favor inténtalo más tarde</p><a href="">Aceptar</a>
                                </div>
                            </div>
                        <?php else : ?>
                            <div class="col_3"></div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
                <hr/>
                <div class="info_box"><span class="icon"></span><span class="text">Recuerda que también puedes acercarte a cualquiera de nuestras sedes, indicando tu cuenta de correo electrónico junto con la tarjeta que desees asociar.</span><a href="#how_asociate_card" name="modal" class="how_asociate_card">¿Cómo asociar mis tarjetas?</a></div>
            </div>
        </div>
        <div id="how_asociate_card" class="modal_box">
          <div class="modal_content"><span class="icon_logo"></span>
            <h3>Para asociar tus tarjetas, sigue los siguientes pasos:</h3>
            <hr/>
            <p>1. Encuentra el número de <strong>10 dígitos </strong>en tu tarjeta física</p><img src="<?php echo URL_RESOURCES ?>front/dist/images/card_detail.png" alt=""/>
            <p>2. Ingresa el número y asignarle el nombre que más prefieras</p><img src="<?php echo URL_RESOURCES ?>front/dist/images/signin_form.png" alt=""/>
          </div>
        </div>
        <div id="mask"></div>
    </div>
</section>