<div class="top_card"><span class="cp_logo"></span>
    <div class="card_title">
        <input type="hidden" id="edit_numero_<?php echo $index; ?>" name="edit_numero_<?php echo $index; ?>" value="<?php echo $row['numero'] ?>"/>
        <input type="text" id="edit_nombre_<?php echo $index; ?>" name="edit_nombre_<?php echo $index; ?>" class="input_name"/>
        <span class="text" id="org_nombre_<?php echo $index; ?>"><?php echo $row['nombre'] ?></span>
        <span class="edit_icon" data-sufix="<?php echo $index; ?>"></span>
    </div>
    <span class="card_number"><?php echo $row['numero'] ?></span>
</div>
<div class="show_more_content">
    <div class="line">
        <div class="left">Dinero<span>?</span></div>
        <div class="right">S/. <?php echo \Common\Helpers\Util::formatDecimal($row['emoneyvalue']); ?></div>
        <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
    </div>
    <div class="line">
        <div class="left">Coney Bonos<span>?</span></div>
        <div class="right">S/. <?php echo \Common\Helpers\Util::formatDecimal($row['bonusvalue']); ?></div>
        <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
    </div>
    <div class="line">
        <div class="left">Coney Bonos Plus<span>?</span></div>
        <div class="right">S/. <?php echo \Common\Helpers\Util::formatDecimal($row['bonusplusvalue']); ?></div>
        <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
    </div>
    <div class="line">
        <div class="left">Tickets<span>?</span></div>
        <div class="right"><?php echo $row['etickets']; ?></div>
        <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
    </div>
    <div class="line">
        <div class="left">Gamepoints<span>?</span></div>
        <div class="right"><?php echo $row['gamepoints']; ?></div>
        <div class="tooltip_bonus">Son regalos que entregamos a nuestros clientes por montos determinados de recargas. Válido para todos los juegos, excepto los que emiten tickets / Cine 6D / Caritas pintadas Yukids</div>
    </div>
</div>
<div class="bottom_card">
    <?php $sumData = array($row['emoneyvalue'], $row['bonusvalue'], $row['bonusplusvalue']); ?>
    <div class="price">S/. <?php echo \Common\Helpers\Util::formatSumaDecimal($sumData) ?></div>
    <a href="javascript:;" class="watch_more">Ver más</a>
    <a href="<?php echo BASE_URL ?>recargas/<?php echo $row['codigo']; ?>" class="recharge">Recargar</a>
</div>
<div class="duplicate_box"><span class="icon"></span>
    <p>El nombre <strong>"Ahijado-tarjeta" </strong>ya se encuentra en tu lista de tarjetas</p><a href="">Aceptar</a>
</div>