- name: Install composer on {{ project_name }}
  composer: command=install working_dir=/opt/fcb/{{ project_name }}

# Set up TrackingEngine database
- name: Create database {{ database }}
  mysql_db: name={{ database }} state=present  

- name: Create user and password for dbs
  mysql_user: name={{ mysql_user }} password={{ mysql_password }} priv=*.*:ALL,GRANT state=present

- name: Copy master sqls
  copy: src=/opt/fcb/{{ project_name }}/scripts/sql/{{item}} dest=/tmp/{{ item }}
  with_items: master_db_sql
  
- name: excute master sql scritps  to {{ database }}
  mysql_db: name={{ database }} state=import target=/tmp/{{ item }}
  with_items: master_db_sql
 
# Set up prject Vitual host
- name: vhost dev.recargas.coneypark.pe
  template: src=dev.recargas.coneypark.pe.conf dest=/etc/httpd/vhosts.d/
  notify: restart httpd
  
- name: host file | update host file
  lineinfile: "dest=/etc/hosts
    insertafter=EOF
    line='127.0.0.1  dev.recargas.coneypark.pe'
    regexp='127.0.0.1  dev.recargas.coneypark.pe'
    state=present"
  notify: restart httpd

# Set Up project configuration
- name: Create vhosts cp Data Directories
  file: path=/opt/fcb/{{ project_name }}/data/{{item}} state=directory owner=root mode=0777
  with_items:
     - cache
     - log

- name: Copy local cp config file
  copy: src={{item}} dest=/root/{{item}} owner=vagrant
  with_items:
     - local.php
     - local.constants.php
       
- command: mv -f /root/local.php /opt/fcb/{{ project_name }}/config/autoload/