<!DOCTYPE html>
<body style="font-family:helvetica">
   <img src="https://gallery.mailchimp.com/7a00016c5a5bcd0057fca67d6/images/401d2863-2198-47ce-b7ab-d6567466d120.png" style="max-width:620px;padding-bottom:0;display:inline!important;vertical-align:bottom" width="564" align="middle">
   <hr style="border-top-width:1px;border-top-style:solid;border-top-color:#fa5500">
   <table width="600">
      <div style="line-height:1.6em">
      <p>Hola <?php echo $this->userData['displayname']; ?></p>
      <p>Recupera tu contraseña haciendo clic en el siguiente enlace:</p>            
      <p><?php $url = $this->server('content') . 'new-password/token/' . $this->token; ?>
        <a href="<?php echo $url; ?>"><?php echo $url; ?></a>
      </p>
   </table>
</body>
</html>