Lo sentimos, no se pudo procesar correctamente tu recarga.

Intentar nuevamente (link)

Contactar al servicio de atención al cliente a


<section class="app_content recargas">
    <div class="box_center">
        <div class="app_box">
            <div class="menu right_active">
                <ul>
                    <li class="first">Beneficios</li>
                    <li>Mis tarjetas</li>
                    <li class="last active">Recargas</li>
                </ul>
            </div>
            <div class="purple_box final_page">
                <p class="yellow_text small_text">Recargas de mis tarjetas</p>
                <div class="steps">
                    <div class="step active">1</div><span class="yellow"></span>
                    <div class="step active">2</div>
                </div>
                <div class="pay_box_white confirmation_box">
                    <h2>¡LO SENTIMOS :(!</h2>
                    <P>No se pudo procesar correctamente tu recarga.</P>
                    <P><a href="<?php echo BASE_URL . 'carrito/pagos'?>">Intentar nuevamente</a></P>
                    <div class="info">
                        <p>Contactar al servicio de atención al cliente </p><a target="_blank" href="http://coneypark.pe/contactos/">Aquí</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
