<section class="app_content recargas">
    <div class="box_center">
        <div class="app_box">
            <div class="menu right_active">
                <ul>
                    <li class="first">Beneficios</li>
                    <li>Mis tarjetas</li>
                    <li class="last active">Recargas</li>
                </ul>
            </div>
            <div class="purple_box final_page">
                <div class="pay_box_white confirmation_box">
                    <h2>¡LO SENTIMOS :(!</h2>
                    <P>No se pudo procesar correctamente tu recarga.</P>

<!--                    --><?php //if ($this->ordenData['pago_metodo'] == \PaymentProcessor\Model\Gateway\Processor\VisaProcessor::ALIAS) :?>
<!--                        Número de recarga: --><?php //echo $this->ordenData['id']; ?>
<!--                        Fecha de recarga: --><?php //echo $this->ordenData['pago_fecha_confirmacion']; ?>
<!--                        Motivo: --><?php //echo $this->ordenData['pago_error_detalle']; ?>
<!--                    --><?php //endif; ?>

                    <P><a href="<?php echo BASE_URL . 'carrito/pagos'?>">Intentar nuevamente</a></P>
                    <div class="info">
                        <p>Contactar al servicio de atención al cliente <a target="_blank" href="http://coneypark.pe/contactos/">Aquí</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
