<?php $this->layout()->title = array('Paquete', 'Listado') ?>
<?php
$this->layout()->breadcrumb = array(
    array('url' => null, 'name' => 'Paquete'),
    array('url' => null, 'name' => 'Listado'),
);
?>

<div class="box">
    <div class="box-header with-border">
        <?php echo $this->partial('paquete/paquete/_buscar.phtml', array('form' => $form)); ?>
    </div>
    <div class="box-body">
        <?php echo $this->showMessenger($this->flashMessenger()->getMessages()); ?>
        <a href="<?php echo BASE_URL; ?>paquete/paquete/crear" class="btn btn-success">Registrar</a>
        <hr class="separator">
        <table id="gridMain" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Coney_bonos</th>
                    <th>Coney_bonos_plus</th>
                    <th>Tickets</th>
                    <th>Monto_total</th>
                    <th>Fecha_creacion</th>
                    <th>Fecha_edicion</th>
                    <th style="max-width: 60px"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($gridList as $row) : ?>
                    <tr>
                        <td><?php echo $row['nombre'] ?></td>
                        <td><?php echo $row['coney_bonos'] ?></td>
                        <td><?php echo $row['coney_bonos_plus'] ?></td>
                        <td><?php echo $row['tickets'] ?></td>
                        <td><?php echo $row['monto_total'] ?></td>
                        <td><?php echo $row['fecha_creacion'] ?></td>
                        <td><?php echo $row['fecha_edicion'] ?></td>
                        <td>
                            <a href="<?php echo BASE_URL ?>paquete/paquete/editar/<?php echo $row['id']; ?>" class="btn btn-primary" title="Editar"><i class="fa fa-edit"></i></a>
                            <a href="<?php echo BASE_URL ?>paquete/paquete/eliminar/<?php echo $row['id']; ?>" class="btn btn-danger delete-remote" title="Eliminar"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#gridMain').DataTable({
            "pageLength": 25,
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": false,
            "info": true,
            "autoWidth": true
        });
        common.deleteRemote();
    });
</script>