<!DOCTYPE html>
<html lang="en"></html>
<head>
  <meta charset="UTF-8"/>
  <title>Document</title>
</head>
<body>
  <table style="width:100%;font-family:Tahoma;margin:0;">
    <tr>
      <td align="center">
        <table style="background:url(http://i.imgur.com/myhkpxS.jpg)" width="700" height="995">
          <tr>
            <td style="height:180px;"></td>
          </tr>
          <tr>
            <td align="center" style="font-size:32px;color:#5218B7;font-weight:bold;height:36px;">¡Hola <?php echo $this->ordenData['usuario_nombres']; ?>!</td>
          </tr>
          <tr>
            <td align="center" style="padding-left:50px;padding-right:50px;color:#8C8C8C;height:50px;font-size:16px;">Tu compra se realizó con éxito. Para más detalles, puedes revisar la información general.</td>
          </tr>
          <tr>
            <td align="center" style="height:60px;font-weight:bold;font-size:15px;color:black;">Número de recarga: <?php echo $this->ordenData['codigo']; ?></td>
          </tr>
          <tr>
            <td align="center" height="200">
              <table width="600" style="font-size:16px;color:black;">
                <tr>
                  <td style="color:#999999;font-size:16px;">Promoción</td>
                  <td style="color:#999999;font-size:16px;">Tarjeta</td>
                  <td style="color:#999999;font-size:16px;">Cantidad</td>
                  <td style="color:#999999;font-size:16px;">Precio</td>
                </tr>
                <tr>
                  <td colspan="4">
                    <div style="width:100%;height:10px;border-bottom:1px dashed lightgray;"></div>
                  </td>
                </tr>
                <?php foreach ($this->ordenDetalleData as $ordenDetalle) :?>
                  <tr>
                    <td><?php echo $ordenDetalle['paquete_titulo1']; ?></td>
                    <td>
                      <div><?php echo $ordenDetalle['tarjeta_nombre']; ?></div>
                      <div style="font-size:15px;"><?php echo $ordenDetalle['tarjeta_numero']; ?></div>
                    </td>
                    <td><?php echo $ordenDetalle['cantidad']; ?></td>
                    <td>S/. <?php echo $ordenDetalle['emoney']; ?></td>
                  </tr>
                  <tr>
                    <td colspan="4">
                      <div style="width:100%;height:10px;border-bottom:1px dashed lightgray;"></div>
                    </td>
                  </tr>
                <?php endforeach; ?>
              </table>
            </td>
          </tr>
          <tr>
            <td align="right" style="padding-right:100px;height:32px;font-weight:bold;font-size:16px;color:black;">TOTAL: S/. <?php echo $this->ordenData['monto']; ?></td>
          </tr>
          <tr>
            <td align="center" style="padding-left:50px;padding-right:50px;color:#8C8C8C;height:100px;font-size:16px;">Para activar tu tarjeta recuerda que primero debes pasarla por el punto de verificación del local en el que deseas jugar y recuerda hacerlo cada vez que cambies de local.</td>
          </tr>
          <tr>
            <td style="padding-left:20px;padding-right:20px;height:1px;">
              <div style="width:100%;border-bottom:1px dashed lightgray;"></div>
            </td>
          </tr>
          <tr>
            <td align="center" style="padding-left:30px;padding-right:30px;height:80px;color:#8C8C8C;font-size:16px;">Para notificar sobre cualquier incidente con tu tarjeta, pérdida o robo, debes comunicárnoslo a través de Contáctanos. </td>
          </tr>
          <tr>
            <td align="center" height="50">
              <table width="600">
                <tr>
                  <td width="30"></td>
                  <td align="right" style="padding-right:10px;"><img src="http://i.imgur.com/iLkaaVI.png" style="display:block;" alt=""/></td>
                  <td width="70" style="font-size:14px;font-weight:bold;color:#797979;font-size:16px;">Promociones y Recargas</td>
                  <td width="30"></td>
                  <td align="right" style="padding-right:10px;"><img src="http://i.imgur.com/gmxNtlS.png" style="display:block;" alt=""/></td>
                  <td width="90" style="font-size:14px;font-weight:bold;color:#797979;font-size:16px;">Actualiza tus datos</td>
                  <td width="30"></td>
                  <td align="right" style="padding-right:10px;"><img src="http://i.imgur.com/lVPfXeQ.png" style="display:block;" alt=""/></td>
                  <td width="70" style="font-size:14px;font-weight:bold;color:#797979;font-size:16px;">Contáctanos</td>
                  <td width="30"></td>
                </tr>
              </table>
            </td>
          </tr>
          <tr>
            <td height="50"></td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>