Estimad@ <?php echo $data['nombres_completo']; ?>; 
<br>
Para cambiar tu contraseña sigue las siguientes instrucciones:
<br>
1.- haz clic en el siguiente link <a href="<?php echo BASE_URL; ?>admin/login/modificar-password?codigo=<?php echo $data['codigo_activar']; ?>">Recuperar Password</a>
<br>
2.- Ingresa tu nueva contraseña.
<br>
3.- Finalmente haz clic en el botón “Aceptar”.
<br>
<br>
Atte.
Equipo Coney Park.
